CS349 WatGUI: a1_main.cpp File Reference
a1_main.cpp File Reference
#include <string.h>
#include "XApplication.h"
#include "Logging.h"
#include "SchemeInterpreter.h"
#include "StopWatch.h"
Functions
int main (int argc, char *argv[])
Variables
const char * scheme_init_fname = "init.scm"
const char * cs349_init_fname = "cs349_init.scm"
Function Documentation
int main (int argc, char * argv[])
Definition at line 14 of file a1_main.cpp.
References cs349_init_fname, cs349::XApplication::GetEventQueue(), LOG_DEBUG, cs349::XApplication::Run(), scheme_init_fname, scheme_interpreter_init(), scheme_interpreter_shutdown(), and cs349::XWindow::SetVisible().
 {
   FLAGS_logtostderr = 1;
   //  FLAGS_log_dir = "./log";
   google::InitGoogleLogging(argv[0]);
   LOG_DEBUG << "Starting up a1_main.cpp";
   XApplication* app = XApplication::GetInstance();
   scheme_interpreter_init(scheme_init_fname, cs349_init_fname, argc, argv);
   StopWatch* stopWatchWindow = new StopWatch(app->GetEventQueue(), Rectangle(0, 0, 200, 50));
   stopWatchWindow->SetVisible(true);
   app->Run();
   vector<XWindow*> windows = XWindow::GetWindowList();
   for (vector<XWindow*>::iterator win = windows.begin(); win != windows.end(); win++) {
     delete (*win);
   }
   delete app;
   return scheme_interpreter_shutdown();
 }
Variable Documentation
const char* cs349_init_fname = "cs349_init.scm"
Definition at line 12 of file a1_main.cpp.
Referenced by main().
const char* scheme_init_fname = "init.scm"
Definition at line 11 of file a1_main.cpp.
Referenced by main().