CS349 WatGUI: cs349::Component Class Reference
cs349::Component Class Reference abstract
#include "Component.h"
Public Member Functions
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual Rectangle GetBounds () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual XWindow * GetParentWindow ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void Repaint (const Rectangle &r)
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetDebugDelay (unsigned long delayMS)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Static Public Member Functions
static Component * GetComponent (long componentNum)
Protected Member Functions
virtual void PaintComponent (Graphics *g)=0
Protected Attributes
vector< Component * > children
All the children of this Component.
Private Attributes
string name
Name is used for interactive debugging, logging.
Rectangle bounds
Component * parent
The parent Component. An XWindow's parent is NULL.
bool visible
Whether the Component should itself and its children.
unsigned long backgroundColor
The color to use for the background when painting.
unsigned long foregroundColor
The color to use for the background when painting.
unsigned long debugDelayMS
long componentNum
Used for scripting to uniquely identify the Component.
Static Private Attributes
static long componentCounter = 1
static map< long, Component * > intComponentMap
Used for scripting.
Detailed Description
Component is one of the biggest classes in the framework as it is the "thing" that users interact with: It represents anything that is visible, and anything that can respond to mouse and key events. It is also the base class for the XWindow class, which represents the actual window.
Components can contain other components (AddComponent). This creates your interactor tree, a hierarchical ordering of interactive components. The root of this interactor tree is an XWindow object.
Components have a location and bounds. This location is in the coordinate system of its parent Component. For example, if component A is a child of the window, and has a location of (5, 5), then that location is relative to the top-left corner of the window's display area. If component A has a child, component B, with a location of (10, 5), then its location in the window is (15, 10), since (10, 5) is relative to the top-left corner of its parent, component A, whose location is (5, 5).
While the location of the component is relative to its parent's coordinate system (i.e., its location), any painting and interaction in the component is assumed to be in the coordinate system of the component itself. For example, say the user clicks at point (17, 20) on the window. In our example above, that point corresponds to point (12, 15) in component A's coordinate system. Thus, when component A receives that mouse event, the coordinates will be relative to the top-left corner of it, rather than in window coordinates.
Because coordinates in events are assumed to be in the coordinate system of the component itself, you are responsible for properly translating coordinates to children coordinates if you pass events on to them. For example, in our example above, (17, 20) in the window coordinate system translates to (12, 15) in component A's corrdinate system, and (2, 10) in component B's coordinate system.
Components respond to events via the HandleKeyEvent and HandleMouseEvent methods.
When the component needs to be painted, the Paint method is called with a Graphics object. All drawing operations occur through the Graphics object. Typically, what you do is write a single implementation of Paint in Component, setting up all relevant variables in the Graphics context object (such as foreground/background color), then call the internal (protected) method, PaintComponent. Subclasses then override PaintComponent to implement custom painting behavior, with the Graphics object already assumed to be configured for drawing for that Component.
Once the Component has painted itself, it should paint its children. Prior to doing this, it needs to set up the Graphic context's AffineTransform to shift the coordinate system to that of each child. This allows each Component to assume that its top-left corner is the origin, and paint accordingly.
Important: Components should only paint themselves (and their children) when their visible attribute is set to true. If a component is not visible, then its children should not be painted, regardless of the state of the visible attribute for them.
Whenever the component changes its visual presentation, it should call one of the "Repaint" methods. The Repaint methods should add a PaintEvent event to the Application event queue to be repainted in the future.
Definition at line 97 of file Component.h.
Constructor & Destructor Documentation
cs349::Component::Component (const string & name)
Parameters
name An arbitrary name to assign this Component to help with debugging and scripting. It is not used anywhere else.
Definition at line 14 of file Component.cpp.
References backgroundColor, componentCounter, componentNum, debugDelayMS, foregroundColor, cs349::XApplication::GetBlackColor(), cs349::XApplication::GetInstance(), cs349::XApplication::GetWhiteColor(), intComponentMap, name, parent, and visible.
   {
     this->name            = name;
     this->parent          = NULL;
     this->visible         = false;
     this->backgroundColor = XApplication::GetInstance()->GetBlackColor();
     this->foregroundColor = XApplication::GetInstance()->GetWhiteColor();
     this->debugDelayMS    = 0;
     componentNum          = componentCounter++;
     intComponentMap[componentNum] = this;
   }
cs349::Component::~Component () virtual
Free up any memory (such as child Components) held by this Component.
Definition at line 26 of file Component.cpp.
References children, componentNum, and intComponentMap.
   {
     // Clear up any memory laying around
     for (vector<Component*>::iterator iter=this->children.begin(); iter != this->children.end(); iter++) {
       delete(*iter);
     }
     this->children.clear();
     // Remove ourself from component map
     intComponentMap.erase(intComponentMap.find(componentNum));
   }
Member Function Documentation
void cs349::Component::AddComponent (Component * child) virtual
Adds a child Component to this Component and sets its parent to this Component. Once added, this Component will take over memory management of the pointer, deleting it should this object be destroyed. However, if the child Component is manually removed via RemoveComponent(), then it no longer is responsible for managing the child's memory.
Parameters
child The Component to add as a child.
Definition at line 41 of file Component.cpp.
References children, and SetParent().
Referenced by main(), and cs349::scheme_component_add_component().
   {
     this->children.push_back(child);
     child->SetParent(this);
   }
unsigned long cs349::Component::GetBackgroundColor () const virtual
Returns
The background color used when painting this Component.
Definition at line 58 of file Component.cpp.
References backgroundColor.
Referenced by cs349::marshall_component_call().
   {
     return this->backgroundColor;
   }
Rectangle cs349::Component::GetBounds () const virtual
Returns
The bounds of this Component: Its x,y position (in the coordinate system of the parent), and its width/height.
Reimplemented in cs349::XWindow.
Definition at line 63 of file Component.cpp.
References bounds.
Referenced by IsPointInComponent(), cs349::marshall_component_call(), and Repaint().
   {
     return this->bounds;
   }
vector< Component * > cs349::Component::GetBreadthFirstInteractorTree () const
Walks the interactor tree for this Component, returning all descendants found via a breadth-first walk of the interactor tree.
Definition at line 89 of file Component.cpp.
References children, and GetParent().
Referenced by cs349::marshall_xwindow_call().
{
     vector<Component*> tree;
     if (const_cast<Component*>(this)->GetParent() == NULL) {
       tree.push_back(const_cast<Component*>(this));
     }
     tree.insert(tree.end(), this->children.begin(), this->children.end());
     for (vector<Component*>::const_iterator child=this->children.begin(); child != this->children.end(); child++) {
       vector<Component*> childTree = (*child)->GetBreadthFirstInteractorTree();
       tree.insert(tree.end(), childTree.begin(), childTree.end());
     }
     return tree;
   }
Component * cs349::Component::GetComponent (long componentNum) static
Gets the Component with the associated number, or NULL if no such Component exists.
Returns
A pointer to the Component with the given component number, or NULL if no such Component exists.
Definition at line 68 of file Component.cpp.
References componentNum, and intComponentMap.
Referenced by cs349::get_component().
{
     if (intComponentMap.find(componentNum) == intComponentMap.end()) {
       return NULL;
     }
     return intComponentMap[componentNum];
   }
long cs349::Component::GetComponentNum () const
Returns the unique number of this Component. Used for scripting.
Returns
The unique number of this Component.
Definition at line 75 of file Component.cpp.
References componentNum.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), cs349::SchemeComponent::HandleMouseEvent(), cs349::marshall_component_call(), cs349::scheme_sc_component_new(), and cs349::XWindow::XWindow().
{
     return this->componentNum;
   }
vector< Component * > cs349::Component::GetDepthFirstInteractorTree () const
Walks the interactor tree for this Component, returning all descendants found via a depth-first walk of the interactor tree.
Definition at line 79 of file Component.cpp.
References children.
Referenced by cs349::marshall_xwindow_call().
{
     vector<Component*> tree;
     tree.push_back(const_cast<Component*>(this));
     for (vector<Component*>::const_iterator child=children.begin(); child != children.end(); child++) {
       vector<Component*> childTree = (*child)->GetDepthFirstInteractorTree();
       tree.insert(tree.end(), childTree.begin(), childTree.end());
     }
     return tree;
   }
unsigned long cs349::Component::GetForegroundColor () const virtual
Returns
The foreground color used when painting this Component.
Definition at line 102 of file Component.cpp.
References foregroundColor.
Referenced by cs349::marshall_component_call().
   {
     return this->foregroundColor;
   }
string cs349::Component::GetName () const virtual
Returns
The name passed in when constructed. Used for scripting and debugging
Definition at line 37 of file Component.cpp.
References name.
Referenced by cs349::marshall_component_call().
{
     return this->name;
   }
Component * cs349::Component::GetParent () virtual
Returns
A pointer to this Component's parent, NULL if it has no parent (which is the case if it is an XWindow).
Definition at line 107 of file Component.cpp.
References parent.
Referenced by GetBreadthFirstInteractorTree(), cs349::marshall_component_call(), and Repaint().
   {
     return this->parent;
   }
XWindow * cs349::Component::GetParentWindow () virtual
Returns
A pointer to the XWindow this Component is within, or NULL if it is not currently in a window.
Reimplemented in cs349::XWindow.
Definition at line 112 of file Component.cpp.
References GetParentWindow(), and parent.
Referenced by GetParentWindow(), cs349::marshall_component_call(), and cs349::SchemeComponent::PaintComponent().
   {
     if (this->parent) {
       return this->parent->GetParentWindow();
     }
     return NULL;
   }
bool cs349::Component::HandleKeyEvent (const KeyEvent & e) virtual
Called when a KeyEvent has been generated.
Returns
true if the event has been handled by this Component or one of its children.
Reimplemented in cs349::SchemeComponent.
Definition at line 120 of file Component.cpp.
References children, and HandleKeyEvent().
Referenced by cs349::KeyEvent::DispatchEvent(), cs349::SchemeComponent::HandleKeyEvent(), and HandleKeyEvent().
   {
     /*
      * Use this as a basic template for how to handle mouse events.
      * Here, we simply pass key events on to child components to see
      * if they can handle the event. As soon as one component handles
      * the event, the method returns.
      */
     for (vector<Component*>::iterator iter=this->children.begin(); iter != this->children.end(); iter++) {
       Component* c = (*iter);
       if (c->HandleKeyEvent(e)) {
         return true;
       }
     }
     return false;
   }
bool cs349::Component::HandleMouseEvent (const MouseEvent & e) virtual
Called when a MouseEvent has been generated within the space of this Component. The coordinates are assumed to be in the Component's coordinate system.
Returns
true if the event has been handled by this Component or one of its children.
Reimplemented in cs349::SchemeComponent, cs349::StopWatch, and Clock.
Definition at line 137 of file Component.cpp.
References LOG_TODO.
Referenced by cs349::MouseEvent::DispatchEvent(), and cs349::SchemeComponent::HandleMouseEvent().
   {
     /*
      * In this default implementation, you should iterate through the
      * children to see if they can handle the event. As soon as one
      * child handles the event (by returning true), the method should
      * return true. If no child can handle the event, it should return
      * false.
      *
      * Some caveats and things to keep in mind:
      * - You shouldn't be able to interact with things you can't see
      * - Points are expected to be in the coordinate system of the
      *   Component (see notes in the header file)
      */
     LOG_TODO << "TODO CS349: Implement Component::HandleMouseEvent (remove when implemented)";
 // TODO CS349
     return false;
   }
bool cs349::Component::IsPointInComponent (const Point & p) const virtual
Tests whether a point, in the parent Component's coordinate system, is within this Component's bounds. Note that this requires converting the Point into the local coordinate system. This method is used for determining where a MouseEvent should be delivered.
Definition at line 158 of file Component.cpp.
References GetBounds(), and cs349::Rectangle::IsPointInRectangle().
Referenced by cs349::scheme_component_is_point_in_component().
   {
     return this->GetBounds().IsPointInRectangle(p);
   }
bool cs349::Component::IsVisible () const virtual
Returns
Whether this Component is visible or not (and hence whether it and its children should be painted or not).
Definition at line 163 of file Component.cpp.
References visible.
Referenced by cs349::marshall_component_call().
   {
     return visible;
   }
void cs349::Component::Paint (Graphics * g) virtual
Called when the Component should paint itself. In this method, this class should configure the Graphics context with all of this Component's settings (such as foreground/background color), then call the protected PaintComponent method.
The Component should assume the Graphics object's AffineTransform has already been transformed to produce a local coordinate system (so the top-left corner of the Component can be assumed to be the origin).
Reimplemented in cs349::StopWatch.
Definition at line 168 of file Component.cpp.
References LOG_TODO.
Referenced by cs349::XWindow::HandlePaintEvent().
   {
     /*
      * This is one of the primary methods of the Component class.
      * In this method, you should:
      * - Think about things like visibility of the Component (is it
      *   visible?)
      * - Save any state of the Graphics context that you'll modify
      * - Prepare for drawing (think about things like
      *   background/foreground colors, clip, and clearing the background)
      * - Call PaintComponent
      * - Make sure children paint themselves
      * - Restore anything you changed in the Graphics context
      */
     LOG_TODO << "TODO CS349: Implement Component::Paint (remove when implemented)";
 // TODO CS349
   }
virtual void cs349::Component::PaintComponent (Graphics * g) protected pure virtual
The method that does the actual painting of the component once the Graphics context object has been set up by the Paint method.
The method is pure virtual because it should be overridden by subclasses to do the actual painting.
Implemented in cs349::XWindow, Clock, and cs349::SchemeComponent.
void cs349::Component::RemoveComponent (Component * child) virtual
Removes the specified Component from the list of children and sets its parent to NULL, if found it found. Does nothing if the child is not in the list of child Components for this Component.
Parameters
child The Component to remove as a child.
Definition at line 47 of file Component.cpp.
References children, and SetParent().
Referenced by cs349::scheme_component_remove_component().
   {
     for (vector<Component*>::iterator i = this->children.begin(); i != this->children.end(); i++) {
       if (*i == child) {
         child->SetParent(NULL);
         this->children.erase(i);
         break;
       }
     }
   }
void cs349::Component::Repaint () virtual
Forces a repaint of this object (its entire area).
Definition at line 187 of file Component.cpp.
References GetBounds(), cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by cs349::SchemeComponent::AddInstruction(), cs349::SchemeComponent::ClearInstructions(), cs349::StopWatch::HandleTimerEvent(), cs349::marshall_component_call(), Repaint(), SetBackgroundColor(), SetBounds(), SetForegroundColor(), cs349::SchemeComponent::SetInstructions(), SetLocation(), SetParent(), SetSize(), and SetVisible().
   {
     Rectangle localBounds = this->GetBounds();
     localBounds.x = 0;
     localBounds.y = 0;
     this->Repaint(localBounds);
   }
void cs349::Component::Repaint (const Rectangle & r) virtual
Forces a repaint of only the specified area of this Component (where the location is assumed to be in the local coordinate system).
Reimplemented in cs349::XWindow.
Definition at line 195 of file Component.cpp.
References GetBounds(), GetParent(), Repaint(), cs349::Rectangle::x, and cs349::Rectangle::y.
   {
     if (this->GetParent() != NULL) {
       Rectangle newRect = r;
       newRect.x += this->GetBounds().x;
       newRect.y += this->GetBounds().y;
       this->GetParent()->Repaint(newRect);
     }
   }
void cs349::Component::SetBackgroundColor (unsigned long c) virtual
Sets the background color of this Component. Triggers a call to Repaint().
Parameters
c The color to use (should be either the black or white color obtained from the Application object.)
Definition at line 205 of file Component.cpp.
References backgroundColor, and Repaint().
Referenced by cs349::scheme_component_set_background_color().
   {
     this->backgroundColor = c;
     this->Repaint();
   }
void cs349::Component::SetBounds (const Rectangle & r) virtual
Sets the bounds of this Component, where location is relative to the parent Component. Triggers a call to Repaint().
Parameters
r The bounds, with location relative to the parent.
Reimplemented in cs349::XWindow.
Definition at line 211 of file Component.cpp.
References bounds, and Repaint().
Referenced by main(), cs349::scheme_component_set_bounds(), cs349::XWindow::SetBounds(), and cs349::XWindow::XWindow().
   {
     this->bounds = r;
     this->Repaint();
   }
void cs349::Component::SetDebugDelay (unsigned long delayMS) virtual
Sets a debug delay for painting.
Definition at line 217 of file Component.cpp.
References debugDelayMS.
Referenced by cs349::marshall_component_call().
{
     debugDelayMS = delayMS;
   }
void cs349::Component::SetForegroundColor (unsigned long c) virtual
Sets the foreground color of this Component. Triggers a call to Repaint().
Parameters
c The color to use (should be either the black or white color obtained from the Application object.)
Definition at line 221 of file Component.cpp.
References foregroundColor, and Repaint().
Referenced by cs349::scheme_component_set_foreground_color().
   {
     this->foregroundColor = c;
     this->Repaint();
   }
void cs349::Component::SetLocation (const Point & p) virtual
Sets the location of this Component, relative to the parent Component. Triggers a call to Repaint().
Parameters
p The new location, relative to the parent.
Reimplemented in cs349::XWindow.
Definition at line 227 of file Component.cpp.
References bounds, Repaint(), cs349::Point::x, cs349::Rectangle::x, cs349::Point::y, and cs349::Rectangle::y.
Referenced by cs349::scheme_component_set_location().
   {
     this->bounds.x = p.x;
     this->bounds.y = p.y;
     this->Repaint();
   }
void cs349::Component::SetParent (Component * parent) virtual
Sets the parent of this Component. Triggers a call to Repaint().
Reimplemented in cs349::XWindow.
Definition at line 234 of file Component.cpp.
References parent, and Repaint().
Referenced by AddComponent(), and RemoveComponent().
   {
     this->parent = parent;
     this->Repaint();
   }
void cs349::Component::SetSize (int width, int height) virtual
Sets the size of this Component. Triggers a call to Repaint().
Reimplemented in cs349::XWindow.
Definition at line 240 of file Component.cpp.
References bounds, cs349::Rectangle::height, Repaint(), and cs349::Rectangle::width.
Referenced by cs349::scheme_component_set_size().
   {
     this->bounds.width = width;
     this->bounds.height = height;
     this->Repaint();
   }
void cs349::Component::SetVisible (bool visible) virtual
Sets whether this Component is visible (painted) or not. Triggers a call to Repaint().
Reimplemented in cs349::XWindow.
Definition at line 247 of file Component.cpp.
References Repaint(), and visible.
Referenced by main(), cs349::scheme_component_set_visible(), and cs349::XWindow::SetVisible().
   {
     this->visible = visible;
     this->Repaint();
   }
Member Data Documentation
unsigned long cs349::Component::backgroundColor private
The color to use for the background when painting.
Definition at line 105 of file Component.h.
Referenced by Component(), GetBackgroundColor(), and SetBackgroundColor().
Rectangle cs349::Component::bounds private
The bounds of the component, where the x,y position is relative to the parent coordinate system
Definition at line 101 of file Component.h.
Referenced by GetBounds(), SetBounds(), SetLocation(), and SetSize().
vector<Component*> cs349::Component::children protected
All the children of this Component.
Definition at line 117 of file Component.h.
Referenced by AddComponent(), GetBreadthFirstInteractorTree(), GetDepthFirstInteractorTree(), HandleKeyEvent(), RemoveComponent(), and ~Component().
long cs349::Component::componentCounter = 1 static private
Used for scripting. Automatically increments each time a new Component is created
Definition at line 112 of file Component.h.
Referenced by Component().
long cs349::Component::componentNum private
Used for scripting to uniquely identify the Component.
Definition at line 110 of file Component.h.
Referenced by Component(), GetComponent(), GetComponentNum(), and ~Component().
unsigned long cs349::Component::debugDelayMS private
Used to debug graphics/painting
Definition at line 107 of file Component.h.
Referenced by Component(), and SetDebugDelay().
unsigned long cs349::Component::foregroundColor private
The color to use for the background when painting.
Definition at line 106 of file Component.h.
Referenced by Component(), GetForegroundColor(), and SetForegroundColor().
map< long, Component * > cs349::Component::intComponentMap static private
Used for scripting.
Definition at line 114 of file Component.h.
Referenced by Component(), GetComponent(), and ~Component().
string cs349::Component::name private
Name is used for interactive debugging, logging.
Definition at line 100 of file Component.h.
Referenced by Component(), and GetName().
Component* cs349::Component::parent private
The parent Component. An XWindow's parent is NULL.
Definition at line 103 of file Component.h.
Referenced by Component(), GetParent(), GetParentWindow(), and SetParent().
bool cs349::Component::visible private
Whether the Component should itself and its children.
Definition at line 104 of file Component.h.
Referenced by Component(), IsVisible(), and SetVisible().
The documentation for this class was generated from the following files:
Component.h
Component.cpp