CS349 WatGUI: cs349::XWindow Class Reference
cs349::XWindow Class Reference
#include "XWindow.h"
Public Member Functions
XWindow (const string &title, const Rectangle &bounds)
virtual ~XWindow ()
virtual Graphics * GetGraphics ()
virtual void HandlePaintEvent (const PaintEvent &e)
virtual void SetTitle (const char *title)
virtual Rectangle GetBounds () const
virtual void PaintComponent (Graphics *g)
virtual XWindow * GetParentWindow ()
virtual void Repaint (const Rectangle &r)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetWindowNum () const
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetDebugDelay (unsigned long delayMS)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Static Public Member Functions
static XWindow * GetXWindowForWindow (Window window)
static vector< XWindow * > GetWindowList ()
static XWindow * GetXWindow (long windowNum)
Static Public Member Functions inherited from cs349::Component
static Component * GetComponent (long componentNum)
Private Attributes
Display * display
Window window
Graphics * graphics
long windowNum
Used for scripting.
Static Private Attributes
static map< long, XWindow * > intWindowMap
Used for scripting interface.
static map< Window, XWindow * > windowMappings
Additional Inherited Members
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
The XWindow class encapsulates an X lib Window object, which represents the actual window users see and interact with.
It is derived from Component, and thus shares much of its functionality, though it must override some of the functionality to make it appropriate to a Window (such as setting the location and bounds).
This class also maintains a mapping of X lib window pointers to our XWindow class pointers. Thus, when X lib creates a new event and specifies a window, you can retrieve the XWindow object corresponding to that window.
Each XWindow object maintains its own Graphics context, which it passes on to its child components to enable drawing into the window.
PaintEvents are passed to the XWindow. Paint events should be analyzed and passed on to children to have them paint themselves. However, only children intersecting the damaged area specified by the PaintEvent should be drawn.
Definition at line 53 of file XWindow.h.
Constructor & Destructor Documentation
cs349::XWindow::XWindow (const string & title, const Rectangle & bounds)
Creates a new window with the given title and bounds.
Definition at line 23 of file XWindow.cpp.
References display, cs349::XApplication::GetBlackColor(), cs349::Component::GetComponentNum(), cs349::XApplication::GetInstance(), cs349::XApplication::GetWhiteColor(), cs349::XApplication::GetXDisplay(), graphics, cs349::Rectangle::height, intWindowMap, cs349::Component::SetBounds(), cs349::Rectangle::width, window, windowMappings, windowNum, cs349::Rectangle::x, and cs349::Rectangle::y.
                                                                  : Component(title)
   {
     this->display = XApplication::GetInstance()->GetXDisplay();
     // Create the window
     this->window = XCreateSimpleWindow( this->display,
                                         DefaultRootWindow(this->display),
                                         bounds.x,
                                         bounds.y,
                                         bounds.width,
                                         bounds.height,
                                         0, // Window border width. Doesn't include width by window manager
                                         XApplication::GetInstance()->GetWhiteColor(),
                                         XApplication::GetInstance()->GetBlackColor());
     // Add ourselves to the mappings
     windowMappings[this->window] = this;
     windowNum = this->GetComponentNum();
     intWindowMap[windowNum] = this;
     XTextProperty xtext;
     xtext.value = (unsigned char*)title.c_str();
     xtext.encoding = XA_STRING;
     xtext.format = 8; // bits per character
     xtext.nitems = strlen(title.c_str()); // string length
     XSetWMName(this->display, this->window, &xtext);
     // Select input events
     XSelectInput(       this->display,
                         this->window,
                         ButtonPressMask
                         | ButtonReleaseMask
                         | KeyPressMask
                         | KeyReleaseMask
                         | ExposureMask
                         | PointerMotionMask
                         | ButtonMotionMask
                         | StructureNotifyMask);
     GC gc = XCreateGC(  display,
                         window,
                         0,
                         0);
     this->graphics = new Graphics(this->display, this->window, gc);
     // Now set our bounds to that which we were set
     XWindowAttributes attr;
     XGetWindowAttributes(this->display, this->window, &attr);
     Component::SetBounds(Rectangle(attr.x, attr.y, attr.width, attr.height));
   }
cs349::XWindow::~XWindow () virtual
Definition at line 75 of file XWindow.cpp.
References display, intWindowMap, window, windowMappings, and windowNum.
   {
     // Remove ourself from the mappings
     windowMappings.erase(windowMappings.find(this->window));
     intWindowMap.erase(intWindowMap.find(windowNum));
     XDestroyWindow(this->display, this->window);
   }
Member Function Documentation
Rectangle cs349::XWindow::GetBounds () const virtual
Returns
The bounds of this Component: Its x,y position (in the coordinate system of the parent), and its width/height.
Reimplemented from cs349::Component.
Definition at line 121 of file XWindow.cpp.
References display, and window.
Referenced by SetLocation(), and SetSize().
{
     Window root;
     int x, y;
     unsigned int width, height, border_width, depth;
     XGetGeometry(display, window, &root, &x, &y, &width, &height, &border_width, &depth);
 // TODO (Mike): This sometimes crashes nondeterministically, so
 // commented out for now
     // Window parent, *children;
     // unsigned int dummy_w, dummy_h, n_children;
     // children = NULL;
     // if (XQueryTree(display, window, &root, &parent, &children, &n_children) == 0) {
     //   LOG_ERROR << "Error: XQueryTree failed";
     // } else {
     //   XGetGeometry(display, parent, &root, &x, &y, &dummy_w, &dummy_h, &border_width, &depth);
     // }
     // if (children) {
     //   XFree(children);
     // }
     return Rectangle(x, y, width, height);
   }
Graphics * cs349::XWindow::GetGraphics () virtual
Returns the graphics context associated with this window
Definition at line 83 of file XWindow.cpp.
References graphics.
Referenced by cs349::marshall_graphics_call().
   {
     return this->graphics;
   }
XWindow * cs349::XWindow::GetParentWindow () virtual
Returns
A pointer to the XWindow this Component is within, or NULL if it is not currently in a window.
Reimplemented from cs349::Component.
Definition at line 88 of file XWindow.cpp.
Referenced by TEST().
   {
     return this;
   }
vector< XWindow * > cs349::XWindow::GetWindowList () static
Gets a list of all XWindow objects that currently exist. Used for scripting interface.
Definition at line 180 of file XWindow.cpp.
References intWindowMap.
Referenced by cs349::scheme_get_xwindow_list().
{
     vector<XWindow*> windowList;
     for (map<long, XWindow*>::const_iterator i=intWindowMap.begin(); i != intWindowMap.end(); i++) {
       windowList.push_back(i->second);
     }
     return windowList;
   }
long cs349::XWindow::GetWindowNum () const
This mapping is used for scripting interfaces. It allows scripts to refer to windows via integers, rather than pointers.
Definition at line 176 of file XWindow.cpp.
References windowNum.
Referenced by cs349::marshall_component_call(), cs349::SchemeComponent::PaintComponent(), and cs349::scheme_xwindow_new().
{
     return this->windowNum;
   }
XWindow * cs349::XWindow::GetXWindow (long windowNum) static
Retrieves a pointer to the XWindow corresponding to the given windowNum, or NULL if no such window exists.
Definition at line 188 of file XWindow.cpp.
References intWindowMap, and windowNum.
Referenced by cs349::get_xwindow().
{
     if (intWindowMap.find(windowNum) == intWindowMap.end()) {
       return NULL;
     }
     return intWindowMap[windowNum];
   }
XWindow * cs349::XWindow::GetXWindowForWindow (Window window) static
Returns a pointer to the XWindow object corresponding to the X lib window pointer
Definition at line 18 of file XWindow.cpp.
References window, and windowMappings.
Referenced by cs349::XApplication::CheckForXEvents().
   {
     return windowMappings[window];
   }
void cs349::XWindow::HandlePaintEvent (const PaintEvent & e) virtual
Called when there are damaged areas that need to be repainted in the window.
Definition at line 93 of file XWindow.cpp.
References cs349::PaintEvent::GetDamagedArea(), graphics, cs349::AffineTransform::MakeIdentity(), cs349::Component::Paint(), cs349::Graphics::SetClipRect(), and cs349::Graphics::SetTransform().
   {
     // Set up Graphics
     this->graphics->SetTransform(AffineTransform::MakeIdentity());
     this->graphics->SetClipRect(e.GetDamagedArea());
     this->Paint(this->graphics); // Calls Component's implementation
   }
void cs349::XWindow::PaintComponent (Graphics * g) virtual
The method that does the actual painting of the component once the Graphics context object has been set up by the Paint method.
The method is pure virtual because it should be overridden by subclasses to do the actual painting.
Implements cs349::Component.
Definition at line 101 of file XWindow.cpp.
{
     ; // no-op -- all painting handled by children
   }
void cs349::XWindow::Repaint (const Rectangle & r) virtual
Forces a repaint of only the specified area of this Component (where the location is assumed to be in the local coordinate system).
Reimplemented from cs349::Component.
Definition at line 142 of file XWindow.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::XApplication::GetEventQueue(), and cs349::XApplication::GetInstance().
{
     XApplication::GetInstance()->GetEventQueue()->AddEventToQueue(new PaintEvent(this, r));
   }
void cs349::XWindow::SetBounds (const Rectangle & r) virtual
Sets the bounds of this Component, where location is relative to the parent Component. Triggers a call to Repaint().
Parameters
r The bounds, with location relative to the parent.
Reimplemented from cs349::Component.
Definition at line 145 of file XWindow.cpp.
References display, cs349::Rectangle::height, cs349::Component::SetBounds(), cs349::Rectangle::width, window, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by SetLocation(), and SetSize().
   {
     int x = (int)r.x;
     int y = (int)r.y;
     unsigned int width = (unsigned int)max(1.0, r.width);
     unsigned int height = (unsigned int)max(1.0, r.height);
     XMoveResizeWindow(display, window, x, y, width, height);
     Component::SetBounds(r);
   }
void cs349::XWindow::SetLocation (const Point & p) virtual
Sets the location of this Component, relative to the parent Component. Triggers a call to Repaint().
Parameters
p The new location, relative to the parent.
Reimplemented from cs349::Component.
Definition at line 154 of file XWindow.cpp.
References GetBounds(), cs349::Rectangle::height, SetBounds(), cs349::Point::x, and cs349::Point::y.
   {
     this->SetBounds(Rectangle(p.x, p.y, this->GetBounds().width, this->GetBounds().height));
   }
void cs349::XWindow::SetParent (Component * parent) virtual
Sets the parent of this Component. Triggers a call to Repaint().
Reimplemented from cs349::Component.
Definition at line 158 of file XWindow.cpp.
References LOG_ERROR.
   {
     LOG_ERROR << "Error: Cannot set parent of an XWindow";
   }
void cs349::XWindow::SetSize (int width, int height) virtual
Sets the size of this Component. Triggers a call to Repaint().
Reimplemented from cs349::Component.
Definition at line 162 of file XWindow.cpp.
References GetBounds(), and SetBounds().
   {
     this->SetBounds(Rectangle(this->GetBounds().x, this->GetBounds().y, width, height));
   }
void cs349::XWindow::SetTitle (const char * title) virtual
Set title of the window
Definition at line 105 of file XWindow.cpp.
References display, and window.
   {
     XSizeHints hints;
     // Set its basic properties
     XSetStandardProperties(     display,
                                 this->window,
                                 title,
                                 title,
                                 None, // Pixmap for icon
                                 NULL,
                                 0,
                                 &hints);
   }
void cs349::XWindow::SetVisible (bool visible) virtual
Sets whether this Component is visible (painted) or not. Triggers a call to Repaint().
Reimplemented from cs349::Component.
Definition at line 166 of file XWindow.cpp.
References display, cs349::Component::SetVisible(), and window.
Referenced by main().
   {
     Component::SetVisible(visible);
     if (visible) {
       XMapRaised(display, window);
     } else {
       XUnmapWindow(display, window);
     }
   }
Member Data Documentation
Display* cs349::XWindow::display private
Definition at line 56 of file XWindow.h.
Referenced by GetBounds(), SetBounds(), SetTitle(), SetVisible(), XWindow(), and ~XWindow().
Graphics* cs349::XWindow::graphics private
Definition at line 58 of file XWindow.h.
Referenced by GetGraphics(), HandlePaintEvent(), and XWindow().
map< long, XWindow * > cs349::XWindow::intWindowMap static private
Used for scripting interface.
Definition at line 61 of file XWindow.h.
Referenced by GetWindowList(), GetXWindow(), XWindow(), and ~XWindow().
Window cs349::XWindow::window private
Definition at line 57 of file XWindow.h.
Referenced by GetBounds(), GetXWindowForWindow(), SetBounds(), SetTitle(), SetVisible(), XWindow(), and ~XWindow().
map< Window, XWindow * > cs349::XWindow::windowMappings static private
Definition at line 62 of file XWindow.h.
Referenced by GetXWindowForWindow(), XWindow(), and ~XWindow().
long cs349::XWindow::windowNum private
Used for scripting.
Definition at line 59 of file XWindow.h.
Referenced by GetWindowNum(), GetXWindow(), XWindow(), and ~XWindow().
The documentation for this class was generated from the following files:
XWindow.h
XWindow.cpp