CS349 WatGUI: cs349::StopWatch Class Reference
cs349::StopWatch Class Reference
#include "StopWatch.h"
Public Member Functions
StopWatch (EventQueue *eventQueue, const Rectangle &bounds)
virtual ~StopWatch ()
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual void Paint (Graphics *g)
virtual void HandleTimerEvent (const cs349::TimerEvent &e)
void Start ()
void Stop ()
bool IsRunning () const
Public Member Functions inherited from cs349::XWindow
XWindow (const string &title, const Rectangle &bounds)
virtual ~XWindow ()
virtual Graphics * GetGraphics ()
virtual void HandlePaintEvent (const PaintEvent &e)
virtual void SetTitle (const char *title)
virtual Rectangle GetBounds () const
virtual void PaintComponent (Graphics *g)
virtual XWindow * GetParentWindow ()
virtual void Repaint (const Rectangle &r)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetWindowNum () const
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Repaint ()
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetDebugDelay (unsigned long delayMS)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Static Private Member Functions
static unsigned long GetCurTime ()
Private Attributes
Timer * timer
unsigned long startTimeMS
bool running
Additional Inherited Members
Static Public Member Functions inherited from cs349::XWindow
static XWindow * GetXWindowForWindow (Window window)
static vector< XWindow * > GetWindowList ()
static XWindow * GetXWindow (long windowNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Private Member Functions inherited from cs349::TimerListener
TimerListener ()
virtual ~TimerListener ()
Detailed Description
Skeleton of a StopWatch class to complete and augment for A1
Definition at line 17 of file StopWatch.h.
Constructor & Destructor Documentation
cs349::StopWatch::StopWatch (EventQueue * eventQueue, const Rectangle & bounds)
StopWatch derives from XWindow and TimerListener. These classes require the following information passed in.
Parameters
eventQueue The XApplication's event queue
bounds The desired location and size of this StopWatch window.
Definition at line 10 of file StopWatch.cpp.
References running, cs349::Timer::Start(), startTimeMS, and timer.
                                                                        : XWindow(string("Stop Watch!"), bounds) {
     this->running = false;
     this->timer = new Timer(eventQueue, 100, true, this);
     timer->Start();
     startTimeMS = 0;
   }
cs349::StopWatch::~StopWatch () virtual
Definition at line 17 of file StopWatch.cpp.
References cs349::Timer::Stop(), and timer.
{
     timer->Stop();
     delete timer;
     timer = NULL;
   }
Member Function Documentation
unsigned long cs349::StopWatch::GetCurTime () static private
Returns the current time in milliseconds.
Definition at line 23 of file StopWatch.cpp.
Referenced by Start().
{
     struct timespec tp;
     clock_gettime(CLOCK_REALTIME, &tp);
     return tp.tv_sec * 1000 + tp.tv_nsec / 1000000;
   }
bool cs349::StopWatch::HandleMouseEvent (const MouseEvent & e) virtual
Overrides Component's HandleMouseEvent method.
Reimplemented from cs349::Component.
Definition at line 33 of file StopWatch.cpp.
References LOG_DEBUG.
{
     // TODO: Remove the following code and add your own event handling
     // code to handle mouse events
     LOG_DEBUG << "Received HandleMouseEvent in StopWatch" << e;
 // TODO CS349
     return true;
   }
void cs349::StopWatch::HandleTimerEvent (const cs349::TimerEvent & e) virtual
Overrides TimerListener's HandleTimerEvent to be able to routinely update the display.
Implements cs349::TimerListener.
Definition at line 42 of file StopWatch.cpp.
References cs349::Component::Repaint(), and running.
{
     if (running) {
       Component::Repaint();
     }
   }
bool cs349::StopWatch::IsRunning () const
Query whether the stopwatch is running or not.
Definition at line 57 of file StopWatch.cpp.
References running.
Referenced by TEST().
{
     return running;
   }
void cs349::StopWatch::Paint (Graphics * g) virtual
Overrides Component's Paint method.
Reimplemented from cs349::Component.
Definition at line 29 of file StopWatch.cpp.
{
 // TODO CS349
   }
void cs349::StopWatch::Start ()
Start the stopwatch
Definition at line 48 of file StopWatch.cpp.
References GetCurTime(), running, and startTimeMS.
{
     this->running = true;
     startTimeMS = GetCurTime();
   }
void cs349::StopWatch::Stop ()
Stop the stopwatch
Definition at line 53 of file StopWatch.cpp.
References running.
{
     this->running = false;
   }
Member Data Documentation
bool cs349::StopWatch::running private
Whether the stopwatch is currently running.
Definition at line 33 of file StopWatch.h.
Referenced by HandleTimerEvent(), IsRunning(), Start(), Stop(), and StopWatch().
unsigned long cs349::StopWatch::startTimeMS private
The time, in milliseconds, that the stopwatch started
Definition at line 28 of file StopWatch.h.
Referenced by Start(), and StopWatch().
Timer* cs349::StopWatch::timer private
Timer used to periodically update the stopwatch's display
Definition at line 23 of file StopWatch.h.
Referenced by StopWatch(), and ~StopWatch().
The documentation for this class was generated from the following files:
StopWatch.h
StopWatch.cpp