CS349 WatGUI: cs349::KeyEvent Class Reference
cs349::KeyEvent Class Reference
#include "KeyEvent.h"
Public Types
enum EventType { keyPress, keyRelease }
Public Member Functions
KeyEvent (XWindow *window, EventType type, XKeyEvent e)
KeyEvent (XWindow *window, EventType type, char key)
virtual ~KeyEvent ()
virtual void DispatchEvent ()
EventType GetType () const
char GetChar () const
Public Member Functions inherited from cs349::ComponentEvent
ComponentEvent (XWindow *window)
virtual ~ComponentEvent ()
virtual XWindow * GetWindow () const
Public Member Functions inherited from cs349::Event
Event ()
virtual ~Event ()
Private Attributes
EventType type
char key
Detailed Description
Encapsulates a key event.
Note: You may need to add functionality that will allow you to get more information than the key's character. For example, the "Escape" key doesn't represent a character.
Definition at line 28 of file KeyEvent.h.
Member Enumeration Documentation
enum cs349::KeyEvent::EventType
Enumerator
keyPress
keyRelease
Definition at line 31 of file KeyEvent.h.
                    {
       keyPress,
       keyRelease
     };
Constructor & Destructor Documentation
cs349::KeyEvent::KeyEvent (XWindow * window, KeyEvent::EventType type, XKeyEvent e)
Creates a new KeyEvent from an XKeyEvent struct.
Definition at line 12 of file KeyEvent.cpp.
References key, and type.
                                                                          : ComponentEvent(window)
   {
     this->type = type;
     XLookupString(&e, &(this->key), 1, NULL, NULL);
   }
cs349::KeyEvent::KeyEvent (XWindow * window, KeyEvent::EventType type, char key)
Creates a new synthetic KeyEvent for the key represented by the given character.
Definition at line 18 of file KeyEvent.cpp.
References key, and type.
                                                                       : ComponentEvent(window)
   {
     this->type = type;
     this->key  = key;
   }
cs349::KeyEvent::~KeyEvent () virtual
Definition at line 24 of file KeyEvent.cpp.
   {
     ; // no-op
   }
Member Function Documentation
void cs349::KeyEvent::DispatchEvent () virtual
Dispatches this event to the XWindow specified when constructed.
Implements cs349::Event.
Definition at line 29 of file KeyEvent.cpp.
References cs349::ComponentEvent::GetWindow(), and cs349::Component::HandleKeyEvent().
   {
     this->GetWindow()->HandleKeyEvent(*this);
   }
char cs349::KeyEvent::GetChar () const
Returns the character representing the key pressed.
Definition at line 34 of file KeyEvent.cpp.
References key.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), and cs349::operator<<().
   {
     return this->key;
   }
KeyEvent::EventType cs349::KeyEvent::GetType () const
Returns whether it was a keyPress or keyRelease event.
Definition at line 39 of file KeyEvent.cpp.
References type.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), and cs349::operator<<().
   {
     return this->type;
   }
Member Data Documentation
char cs349::KeyEvent::key private
Definition at line 37 of file KeyEvent.h.
Referenced by GetChar(), and KeyEvent().
EventType cs349::KeyEvent::type private
Definition at line 36 of file KeyEvent.h.
Referenced by GetType(), and KeyEvent().
The documentation for this class was generated from the following files:
KeyEvent.h
KeyEvent.cpp