CS349 WatGUI: cs349::SchemeComponent Class Reference
cs349::SchemeComponent Class Reference
#include "SchemeComponent.h"
Public Member Functions
SchemeComponent (const string &name)
void ClearInstructions ()
vector< string > GetInstructions () const
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool HandleMouseEvent (const MouseEvent &e)
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual Rectangle GetBounds () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual XWindow * GetParentWindow ()
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Paint (Graphics *g)
virtual void Repaint ()
virtual void Repaint (const Rectangle &r)
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetDebugDelay (unsigned long delayMS)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Protected Member Functions
virtual void PaintComponent (Graphics *g)
Private Member Functions
void AddInstruction (const string &op_args)
void SetInstructions (const vector< string > &instructions)
Private Attributes
vector< string > instructions
Friends
pointer scheme_sc_component_add_instruction (scheme *sc, pointer args, SchemeComponent *component)
pointer scheme_sc_component_set_instructions (scheme *sc, pointer args, SchemeComponent *component)
Additional Inherited Members
Static Public Member Functions inherited from cs349::Component
static Component * GetComponent (long componentNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
SchemeComponent is a Component that can execute drawing operations via Scheme code. Most methods defined in Graphics can be added as instructions that are executed when PaintComponent() is called. Data marshalling is handled in SchemeGUI.cpp
Definition at line 20 of file SchemeComponent.h.
Constructor & Destructor Documentation
cs349::SchemeComponent::SchemeComponent (const string & name)
Definition at line 12 of file SchemeComponent.cpp.
     : Component(name)
   {
     ; // no-op
   }
Member Function Documentation
void cs349::SchemeComponent::AddInstruction (const string & op_args) private
Definition at line 28 of file SchemeComponent.cpp.
References instructions, and cs349::Component::Repaint().
Referenced by cs349::scheme_sc_component_add_instruction().
{
     instructions.push_back(op_args);
     this->Repaint();
   }
void cs349::SchemeComponent::ClearInstructions ()
Clears any Scheme instructions stored by this component.
Definition at line 33 of file SchemeComponent.cpp.
References instructions, and cs349::Component::Repaint().
Referenced by cs349::marshall_sc_component_call().
{
     instructions.erase(instructions.begin(), instructions.end());
     this->Repaint();
   }
vector< string > cs349::SchemeComponent::GetInstructions () const
Gets all of the Scheme instructions stored by this component.
Definition at line 38 of file SchemeComponent.cpp.
References instructions.
Referenced by cs349::marshall_sc_component_call().
{
     return instructions;
   }
bool cs349::SchemeComponent::HandleKeyEvent (const KeyEvent & e) virtual
Overrides Component::HandleKeyEvent to notify Scheme interpreter that a Scheme component has received a KeyEvent.
Reimplemented from cs349::Component.
Definition at line 48 of file SchemeComponent.cpp.
References cs349::KeyEvent::GetChar(), cs349::Component::GetComponentNum(), cs349::KeyEvent::GetType(), cs349::Component::HandleKeyEvent(), cs349::KeyEvent::keyPress, cs349::KeyEvent::keyRelease, LOG_ERROR, sc, and scheme_interpreter_evaluate_string().
   {
     bool componentResult = Component::HandleKeyEvent(e);
     stringstream ss;
     ss << "(scheme-component-handle-key-event " << this->GetComponentNum() << " ";
     switch (e.GetType()) {
     case KeyEvent::keyPress:
       ss << "'key-press";
       break;
     case KeyEvent::keyRelease:
       ss << "'key-release";
       break;
     default:
       LOG_ERROR << "Error: Unknown KeyEvent type: " << e.GetType();
       return componentResult;
     }
     ss << " #\\" << e.GetChar();
     ss << ")";
     scheme* sc = NULL;
     pointer result;
     int error;
     bool schemeResult = false;
     error = scheme_interpreter_evaluate_string(ss.str().c_str(), &sc, &result);
     if (error) {
       LOG_ERROR << "Error evaluating string: " << ss.str();
     } else {
       if (sc != NULL) {
         schemeResult = result == sc->T;
       } else {
         LOG_ERROR << "Error: No pointer Scheme interpreter returned;";
       }
     }
     return componentResult || schemeResult;
   }
bool cs349::SchemeComponent::HandleMouseEvent (const MouseEvent & e) virtual
Overrides Component::HandleMouseEvent to notify Scheme interpreter that a Scheme component has received a MouseEvent.
Reimplemented from cs349::Component.
Definition at line 88 of file SchemeComponent.cpp.
References cs349::Component::GetComponentNum(), cs349::MouseEvent::GetType(), cs349::MouseEvent::GetWhere(), cs349::Component::HandleMouseEvent(), LOG_ERROR, cs349::MouseEvent::mouseDown, cs349::MouseEvent::mouseDrag, cs349::MouseEvent::mouseMove, cs349::MouseEvent::mouseUp, sc, scheme_interpreter_evaluate_string(), cs349::Point::x, and cs349::Point::y.
   {
     bool componentResult = Component::HandleMouseEvent(e);
     stringstream ss;
     ss << "(scheme-component-handle-mouse-event " << this->GetComponentNum() << " ";
     switch (e.GetType()) {
     case MouseEvent::mouseDown:
       ss << "'mouse-down";
       break;
     case MouseEvent::mouseUp:
       ss << "'mouse-up";
       break;
     case MouseEvent::mouseMove:
       ss << "'mouse-move";
       break;
     case MouseEvent::mouseDrag:
       ss << "'mouse-drag";
       break;
     default:
       LOG_ERROR << "Error: Unknown MouseEvent type: " << e.GetType();
       return componentResult;
     }
     ss << " (list " << e.GetWhere().x << " " << e.GetWhere().y;
     ss << "))";
     scheme* sc = NULL;
     pointer result;
     int error;
     bool schemeResult = false;
     error = scheme_interpreter_evaluate_string(ss.str().c_str(), &sc, &result);
     if (error) {
       LOG_ERROR << "Error evaluating string: " << ss.str();
     } else {
       if (sc != NULL) {
         schemeResult = result == sc->T;
       } else {
         LOG_ERROR << "Error: No pointer Scheme interpreter returned;";
       }
     }
     return componentResult || schemeResult;
   }
void cs349::SchemeComponent::PaintComponent (Graphics * g) protected virtual
The method that does the actual painting of the component once the Graphics context object has been set up by the Paint method.
The method is pure virtual because it should be overridden by subclasses to do the actual painting.
Implements cs349::Component.
Definition at line 18 of file SchemeComponent.cpp.
References cs349::Component::GetParentWindow(), cs349::XWindow::GetWindowNum(), instructions, and scheme_interpreter_execute_graphics_instruction().
{
     XWindow* win = this->GetParentWindow();
     if (win == NULL) {
       return;
     }
     for (vector<string>::iterator i = instructions.begin(); i != instructions.end(); i++) {
       scheme_interpreter_execute_graphics_instruction(win->GetWindowNum(), i->c_str());
     }
   }
void cs349::SchemeComponent::SetInstructions (const vector< string > & instructions) private
Definition at line 42 of file SchemeComponent.cpp.
References instructions, and cs349::Component::Repaint().
Referenced by cs349::scheme_sc_component_set_instructions().
{
     this->instructions = instructions;
     this->Repaint();
   }
Friends And Related Function Documentation
pointer scheme_sc_component_add_instruction (scheme * sc, pointer args, SchemeComponent * component) friend
pointer scheme_sc_component_set_instructions (scheme * sc, pointer args, SchemeComponent * component) friend
Member Data Documentation
vector<string> cs349::SchemeComponent::instructions private
Definition at line 22 of file SchemeComponent.h.
Referenced by AddInstruction(), ClearInstructions(), GetInstructions(), PaintComponent(), and SetInstructions().
The documentation for this class was generated from the following files:
SchemeComponent.h
SchemeComponent.cpp