CS349 WatGUI: cs349::MouseEvent Class Reference
cs349::MouseEvent Class Reference
#include "MouseEvent.h"
Public Types
enum EventType { mouseUp, mouseDown, mouseMove, mouseDrag }
Public Member Functions
MouseEvent (XWindow *window, EventType eventType, const Point &where)
virtual ~MouseEvent ()
virtual void DispatchEvent ()
EventType GetType () const
Point GetWhere () const
Public Member Functions inherited from cs349::ComponentEvent
ComponentEvent (XWindow *window)
virtual ~ComponentEvent ()
virtual XWindow * GetWindow () const
Public Member Functions inherited from cs349::Event
Event ()
virtual ~Event ()
Private Attributes
EventType type
Point where
Detailed Description
Encapsulates a mouse event.
Coordinates are assumed to be in the coordinate system of the component to which the event is delivered. This requires creating a new MouseEvent when passing it down the interactor tree.
Definition at line 29 of file MouseEvent.h.
Member Enumeration Documentation
enum cs349::MouseEvent::EventType
Enumerator
mouseUp
mouseDown
mouseMove
mouseDrag
Definition at line 32 of file MouseEvent.h.
                    {
       mouseUp,
       mouseDown,
       mouseMove,
       mouseDrag
     };
Constructor & Destructor Documentation
cs349::MouseEvent::MouseEvent (XWindow * window, EventType eventType, const Point & where)
Constructs a MouseEvent of the given type, at the given location.
Parameters
window The XWindow corresponding to this MouseEvent
eventType The type of MouseEvent
where The location of the MouseEvent, in coordinates local to the Component where this event is delivered.
Definition at line 10 of file MouseEvent.cpp.
References type, and where.
                                                                              : ComponentEvent(window)
   {
     this->type = type;
     this->where = where;
   }
cs349::MouseEvent::~MouseEvent () virtual
Definition at line 16 of file MouseEvent.cpp.
   {
     ; // no-op
   }
Member Function Documentation
void cs349::MouseEvent::DispatchEvent () virtual
Dispatches this event to the XWindow specified when constructed.
Implements cs349::Event.
Definition at line 21 of file MouseEvent.cpp.
References cs349::ComponentEvent::GetWindow(), and cs349::Component::HandleMouseEvent().
   {
     this->GetWindow()->HandleMouseEvent(*this);
   }
MouseEvent::EventType cs349::MouseEvent::GetType () const
Returns
The type of MouseEvent
Definition at line 26 of file MouseEvent.cpp.
References type.
Referenced by Clock::HandleMouseEvent(), cs349::SchemeComponent::HandleMouseEvent(), and cs349::operator<<().
   {
     return this->type;
   }
Point cs349::MouseEvent::GetWhere () const
Returns
Location of this mouse event, in coordinates local to the Component to which this event is delivered.
Definition at line 31 of file MouseEvent.cpp.
References where.
Referenced by cs349::SchemeComponent::HandleMouseEvent(), and cs349::operator<<().
   {
     return this->where;
   }
Member Data Documentation
EventType cs349::MouseEvent::type private
Definition at line 40 of file MouseEvent.h.
Referenced by GetType(), and MouseEvent().
Point cs349::MouseEvent::where private
Definition at line 41 of file MouseEvent.h.
Referenced by GetWhere(), and MouseEvent().
The documentation for this class was generated from the following files:
MouseEvent.h
MouseEvent.cpp