CS349 WatGUI: cs349::Timer Class Reference
cs349::Timer Class Reference
#include "Timer.h"
Public Member Functions
Timer (EventQueue *eventQueue, unsigned long delayMS, bool repeat, TimerListener *l)
virtual ~Timer ()
void AddTimerListener (TimerListener *l)
void RemoveTimerListener (TimerListener *l)
void Start ()
void Stop ()
bool IsRunning () const
Private Member Functions
void ServiceTimer ()
Static Private Member Functions
static unsigned long GetCurrentTime ()
Private Attributes
EventQueue * eventQueue
unsigned long delayMS
The delay in milliseconds.
unsigned long lastTime
bool repeat
Whether it's a repeating timer.
bool running
Whether it's currently running.
vector< TimerListener * > timerListeners
Friends
class EventQueue
class TimerEvent
Detailed Description
A basic timer class that integrates with an EventQueue object. To use, instantiate a Timer with the delay specified in milliseconds, indicate whether the timer repeats, and specify the object that will be called whenever the timer triggers.
You should not need to modify this class to make it work, though you must ensure that the EventQueue object regularly calls the "ServiceTimer" method in its ProcessNextEvent() method to ensure the Timer can check whether enough time has elapsed to notify its listeners.
You must explicitly call "Start" to start the timer.
Caveats: Precision of the timer will be limited to how often ServiceTimer() is called by EventQueue via ProcessNextEvent. The timer is not guaranteed to notify its listeners at the elapsed time specified.
As with other objects, you are responsible for deallocating any memory for this Timer * when you are finished with it.
Definition at line 44 of file Timer.h.
Constructor & Destructor Documentation
cs349::Timer::Timer (EventQueue * eventQueue, unsigned long delayMS, bool repeat, TimerListener * l)
Construct a new Timer object.
Parameters
eventQueue The EventQueue this Timer will be associated with
delayMS The delay, in milliseconds, before this Timer triggers once started
repeat Whether the Timer should reset itself and start over once the initial time has elapsed
l The TimerListener object that will be notified when this Timer triggers
Definition at line 11 of file Timer.cpp.
References delayMS, eventQueue, repeat, running, and timerListeners.
   {
     this->eventQueue = eventQueue;
     this->delayMS    = delayMS;
     this->repeat     = repeat;
     this->timerListeners.push_back(l);
     this->running    = false;
   }
cs349::Timer::~Timer () virtual
On destruction, removes itself from the EventQueue's list of timers
Definition at line 20 of file Timer.cpp.
References eventQueue, and cs349::EventQueue::RemoveTimer().
   {
     if (eventQueue) {
       eventQueue->RemoveTimer(this);
     }
   }
Member Function Documentation
void cs349::Timer::AddTimerListener (TimerListener * l)
Add a TimerListener object to be notified when the Timer triggers.
Definition at line 27 of file Timer.cpp.
References timerListeners.
   {
     this->timerListeners.push_back(l);
   }
unsigned long cs349::Timer::GetCurrentTime () static private
Definition at line 32 of file Timer.cpp.
Referenced by ServiceTimer(), and Start().
   {
     struct timespec tp;
     clock_gettime(CLOCK_REALTIME, &tp);
     return tp.tv_sec * 1000 + tp.tv_nsec / 1000000;
   }
bool cs349::Timer::IsRunning () const
Returns whether the Timer is currently running.
Definition at line 39 of file Timer.cpp.
References running.
Referenced by TEST().
   {
     return this->running;
   }
void cs349::Timer::RemoveTimerListener (TimerListener * l)
Remove a TimerListener object
Definition at line 44 of file Timer.cpp.
References timerListeners.
   {
     remove(this->timerListeners.begin(), this->timerListeners.end(), l);
   }
void cs349::Timer::ServiceTimer () private
Called by the Application from its event loop to enable the Timer to check whether it needs to create a TimerEvent
Definition at line 49 of file Timer.cpp.
References cs349::EventQueue::AddEventToQueue(), delayMS, eventQueue, GetCurrentTime(), lastTime, repeat, running, Stop(), and TimerEvent.
Referenced by cs349::EventQueue::ProcessNextEvent().
   {
     if (!this->running) {
       return;
     }
     unsigned long elapsedTimeMS = GetCurrentTime() - this->lastTime;
     if (elapsedTimeMS > this->delayMS) {
       this->lastTime = GetCurrentTime();
       eventQueue->AddEventToQueue(new TimerEvent(this));
       if (!this->repeat) {
         this->Stop();
       }
     }
   }
void cs349::Timer::Start ()
Starts the Timer and adds it to the EventQueue's list of Timers.
Definition at line 64 of file Timer.cpp.
References cs349::EventQueue::AddTimer(), eventQueue, GetCurrentTime(), lastTime, and running.
Referenced by cs349::StopWatch::StopWatch(), and TEST().
   {
     if (!this->running) {
       eventQueue->AddTimer(this);
       this->lastTime = GetCurrentTime();
       this->running = true;
     }
   }
void cs349::Timer::Stop ()
Stops the Timer and removes in from the EventQueue's list of Timers.
Definition at line 73 of file Timer.cpp.
References eventQueue, cs349::EventQueue::RemoveTimer(), and running.
Referenced by ServiceTimer(), and cs349::StopWatch::~StopWatch().
   {
     if (this->running) {
       this->running = false;
       eventQueue->RemoveTimer(this);
     }
   }
Friends And Related Function Documentation
friend class EventQueue friend
Definition at line 64 of file Timer.h.
friend class TimerEvent friend
Definition at line 65 of file Timer.h.
Referenced by ServiceTimer().
Member Data Documentation
unsigned long cs349::Timer::delayMS private
The delay in milliseconds.
Definition at line 49 of file Timer.h.
Referenced by ServiceTimer(), and Timer().
EventQueue* cs349::Timer::eventQueue private
The event queue that this is a part of
Definition at line 47 of file Timer.h.
Referenced by ServiceTimer(), Start(), Stop(), Timer(), and ~Timer().
unsigned long cs349::Timer::lastTime private
Definition at line 50 of file Timer.h.
Referenced by ServiceTimer(), and Start().
bool cs349::Timer::repeat private
Whether it's a repeating timer.
Definition at line 51 of file Timer.h.
Referenced by ServiceTimer(), and Timer().
bool cs349::Timer::running private
Whether it's currently running.
Definition at line 52 of file Timer.h.
Referenced by IsRunning(), ServiceTimer(), Start(), Stop(), and Timer().
vector<TimerListener*> cs349::Timer::timerListeners private
TimerListeners that are notified when the timer triggers
Definition at line 53 of file Timer.h.
Referenced by AddTimerListener(), cs349::TimerEvent::DispatchEvent(), RemoveTimerListener(), and Timer().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp