CS349 WatGUI: cs349::AffineTransform Class Reference
cs349::AffineTransform Class Reference
#include "AffineTransform.h"
Public Member Functions
AffineTransform ()
AffineTransform (const SquareMatrix &m)
AffineTransform (const AffineTransform &t)
AffineTransform operator* (const AffineTransform &right) const
Point operator* (const Point &point) const
AffineTransform GetInverse () const
SquareMatrix GetMatrix () const
Static Public Member Functions
static AffineTransform MakeIdentity ()
static AffineTransform MakeRotation (double theta)
static AffineTransform MakeRotationInDegrees (double degrees)
static AffineTransform MakeScale (double scaleX, double scaleY)
static AffineTransform MakeTranslation (double translateX, double translateY)
Private Attributes
SquareMatrix transform
Detailed Description
Object for representing affine transforms and applying them to points. AffineTransform objects are immutable.
Definition at line 23 of file AffineTransform.h.
Constructor & Destructor Documentation
cs349::AffineTransform::AffineTransform ()
Creates an affine transform that is the identity matrix.
Definition at line 8 of file AffineTransform.cpp.
   {
     this->transform.makeUnity();
   }
cs349::AffineTransform::AffineTransform (const SquareMatrix & m)
Creates an affine transform with the given matrix.
Definition at line 13 of file AffineTransform.cpp.
   {
     this->transform = m;
   }
cs349::AffineTransform::AffineTransform (const AffineTransform & t)
Copy constructor for AffineTransform
Definition at line 18 of file AffineTransform.cpp.
References transform.
   {
     this->transform = t.transform;
   }
Member Function Documentation
AffineTransform cs349::AffineTransform::GetInverse () const
Returns the inverse of this matrix. You probably won't need this (and if you think you do, ask a TA or instructor).
Definition at line 82 of file AffineTransform.cpp.
Referenced by cs349::Graphics::GetClipRect(), and scheme_affine_invert().
   {
     SquareMatrix t = this->transform;
     t.makeInverse();
     return AffineTransform(t);
   }
SquareMatrix cs349::AffineTransform::GetMatrix () const
Returns the underlying matrix of this AffineTransform. You probably won't need this (and if you think you do, ask a TA or instructor).
Definition at line 29 of file AffineTransform.cpp.
Referenced by EqualToMatrix(), EqualTransforms(), cs349::marshall_graphics_call(), scheme_affine_invert(), ValidateIdentity(), ValidateRotation(), ValidateScale(), and ValidateTranslation().
   {
     return this->transform;
   }
AffineTransform cs349::AffineTransform::MakeIdentity () static
Creates an affine transform that is the identity matrix.
Definition at line 24 of file AffineTransform.cpp.
Referenced by cs349::XWindow::HandlePaintEvent(), scheme_affine_make_identity(), and TEST().
   {
     return AffineTransform();
   }
AffineTransform cs349::AffineTransform::MakeRotation (double theta) static
Creates an affine transform representing a rotation matrix.
Parameters
theta The angle, in radians
Definition at line 34 of file AffineTransform.cpp.
References transform.
Referenced by scheme_affine_make_rotation(), and TEST().
   {
     // We assume multiplication of a point represented as a column vector.
     AffineTransform t;
     double cosTheta = cos(theta);
     double sinTheta = sin(theta);
     t.transform[0][0] = cosTheta;
     t.transform[0][1] = -1 * sinTheta;
     t.transform[1][0] = sinTheta;
     t.transform[1][1] = cosTheta;
     return t;
   }
AffineTransform cs349::AffineTransform::MakeRotationInDegrees (double degrees) static
Creates an affine transform representing a rotation matrix.
Parameters
degrees The angle, in degrees
Definition at line 47 of file AffineTransform.cpp.
References PI.
Referenced by TEST().
{
     return MakeRotation(degrees / 180.0 * PI);
   }
AffineTransform cs349::AffineTransform::MakeScale (double scaleX, double scaleY) static
Creates an affine transform representing a scale matrix.
Parameters
scaleX The amount to scale along x axis
scaleY The amount to scale along y axis
Definition at line 51 of file AffineTransform.cpp.
References transform.
Referenced by scheme_affine_make_scale(), and TEST().
   {
     AffineTransform t;
     t.transform[0][0] = scaleX;
     t.transform[1][1] = scaleY;
     return t;
   }
AffineTransform cs349::AffineTransform::MakeTranslation (double translateX, double translateY) static
Creates an affine transform representing a translation matrix.
Parameters
translateX The amount to translate along the x axis
translateY The amount to translate along the y axis
Definition at line 59 of file AffineTransform.cpp.
References transform.
Referenced by scheme_affine_make_translate(), and TEST().
   {
     AffineTransform t;
     t.transform[0][2] = translateX;
     t.transform[1][2] = translateY;
     return t;
   }
AffineTransform cs349::AffineTransform::operator* (const AffineTransform & right) const
Multiplies this matrix by the one passed in and returns the result as a new AffineTransform object. The order of matrix multiplications is precisely as expected by this operator:
this_matrix * right
Definition at line 67 of file AffineTransform.cpp.
References transform.
{
     return AffineTransform(this->transform * r.transform);
   }
Point cs349::AffineTransform::operator* (const Point & point) const
Multiplies this AffineTransform and the point provided. The point is turned into a column vector using homogenous coordinates before multiplication, and is equivalent to:
this_matrix * point
Definition at line 71 of file AffineTransform.cpp.
References cs349::Point::x, and cs349::Point::y.
   {
     PointVector pointVector;
     pointVector[0][0] = p.x;
     pointVector[1][0] = p.y;
     pointVector[2][0] = 1;
     PointVector transformedPoint = this->transform * pointVector;
     return Point(transformedPoint[0][0], transformedPoint[1][0]);
   }
Member Data Documentation
SquareMatrix cs349::AffineTransform::transform private
Definition at line 26 of file AffineTransform.h.
Referenced by AffineTransform(), MakeRotation(), MakeScale(), MakeTranslation(), and operator*().
The documentation for this class was generated from the following files:
AffineTransform.h
AffineTransform.cpp