CS349 WatGUI: cs349::XApplication Class Reference
cs349::XApplication Class Reference
#include "XApplication.h"
Public Member Functions
~XApplication ()
Display * GetXDisplay () const
int GetDefaultScreen () const
unsigned long GetBlackColor () const
unsigned long GetWhiteColor () const
EventQueue * GetEventQueue ()
void Run ()
void Quit ()
Static Public Member Functions
static XApplication * GetInstance ()
Private Member Functions
XApplication ()
int HandleXError (Display *display)
void CheckForXEvents ()
Private Attributes
Display * display
A pointer to the display.
int screen
Represents the default screen to display on.
bool quit
Whether the app should continue to run, or quit.
EventQueue eventQueue
The event queue used to manage events.
Static Private Attributes
static XApplication * s_Instance = NULL
Friends
int ErrorHandler (Display *display)
Detailed Description
XApplication is the back-bone of your application. XApplication does the following:
Initializes and maintains the connection with X, and provides access to important X variables (such as the values for black and white colors).
Implements the event loop via its Run() method. In the event loop, new events are received from X, packaged up as our own custom Event objects, and added to the EventQueue object. Events are then peeled off the event queue in FIFO order, and asked to deliver themselves.
XApplication is a singleton: There is only one instance of it in existence throughout the lifetime of the application. As such, you don't directly instantiate the XApplication object. Instead, you call XApplication::GetInstance().
Definition at line 33 of file XApplication.h.
Constructor & Destructor Documentation
cs349::XApplication::XApplication () private
Private constructor so only one instance can be created (it's a singleton). Use GetInstance() to construct/get a pointer to the actual object.
Definition at line 29 of file XApplication.cpp.
References display, LOG_FATAL, quit, and screen.
Referenced by GetInstance().
   {
     // Initialize the X display and get the default screen
     display = XOpenDisplay("");
     if (!display) {
       LOG_FATAL << "Error: Couldn't open X display";
       return;
     }
     screen = DefaultScreen(display);
     quit   = false;
   }
cs349::XApplication::~XApplication ()
Definition at line 41 of file XApplication.cpp.
   {
     ; // No-op
   }
Member Function Documentation
void cs349::XApplication::CheckForXEvents () private
This method checks whether any X events are pending. If so, it packages them up as our own events and adds them to the eventQueue.
Definition at line 104 of file XApplication.cpp.
References cs349::EventQueue::AddEventToQueue(), display, eventQueue, cs349::XWindow::GetXWindowForWindow(), and LOG_TODO.
{
     /*
      * TODO for CS349 assignment:
      * Check if there is an X event pending. If so, package it up
      * using our own Event classes, and add it to the eventQueue.
      *
      * See the documentation at
      * http://tronche.com/gui/x/xlib/events/types.html to learn how to
      * identify the different types of X events.
      *
      * One thing you may be wondering is why we package up an event
      * and add it to the event queue, rather than dispatching it right
      * away. The reason is that events may be added to the queue by
      * other objects (such as TimerEvents). Thus, to preserve proper
      * temporal ordering of events, you need to add events to the
      * queue and dispath them one by one.
      */
     if (XPending(this->display)) {
       // Get event, package it up, add it to the queue
       XEvent event;
       Event* newEvent = NULL;
       XNextEvent(this->display, &event);
       XWindow* window = XWindow::GetXWindowForWindow(event.xany.window);
       LOG_TODO << "TODO CS349: Implement XApplication::CheckForXEvents (remove when implemented)";
       switch (event.type) {
 // TODO CS349
       case DestroyNotify:
         LOG(INFO) << "Destroy notify event received";
         break;
       }
       if (newEvent) {
         eventQueue.AddEventToQueue(newEvent);
       }
     }
   }
unsigned long cs349::XApplication::GetBlackColor () const
Gets the value representing black from this X server.
Definition at line 55 of file XApplication.cpp.
References display, and screen.
Referenced by cs349::Component::Component(), and cs349::XWindow::XWindow().
   {
     return BlackPixel(this->display, this->screen);
   }
int cs349::XApplication::GetDefaultScreen () const
Retrieves the default screen for this X server.
Definition at line 60 of file XApplication.cpp.
References screen.
   {
     return this->screen;
   }
EventQueue * cs349::XApplication::GetEventQueue ()
Returns a pointer to this app's EventQueue object, to be able to add Events to it.
Definition at line 65 of file XApplication.cpp.
References eventQueue.
Referenced by main(), cs349::XWindow::Repaint(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), and TEST().
   {
     return &eventQueue;
   }
XApplication * cs349::XApplication::GetInstance () static
Gets a pointer to the XApplication object (constructing it, if necessary).
Definition at line 46 of file XApplication.cpp.
References s_Instance, and XApplication().
Referenced by cs349::Component::Component(), cs349::Graphics::DebugDelay(), cs349::ErrorHandler(), cs349::XWindow::Repaint(), cs349::scheme_call_c_function(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), TEST(), and cs349::XWindow::XWindow().
   {
     if (!XApplication::s_Instance) {
       s_Instance = new XApplication();
     }
     return s_Instance;
   }
unsigned long cs349::XApplication::GetWhiteColor () const
Gets the value representing white from this X server.
Definition at line 70 of file XApplication.cpp.
References display, and screen.
Referenced by cs349::Component::Component(), and cs349::XWindow::XWindow().
   {
     return WhitePixel(this->display, this->screen);
   }
Display * cs349::XApplication::GetXDisplay () const
Retrieves the X Display for this X server.
Definition at line 75 of file XApplication.cpp.
References display.
Referenced by cs349::XWindow::XWindow().
   {
     return this->display;
   }
int cs349::XApplication::HandleXError (Display * display) private
Definition at line 80 of file XApplication.cpp.
References scheme_interpreter_shutdown().
Referenced by cs349::ErrorHandler().
   {
     /*
       This method is called whenever there is a serious
       X error. This method will be called when the user
       manually closes the window. You could clean up
       the event queue, release memory, and anything else
       needed before the application quits, because once
       this method returns, X will forcibly terminate
       the entire application.
     */
     // Shut down the Scheme interpreter so it cleanly exits readline.
     // Otherwise, it puts the terminal in a funky state
     scheme_interpreter_shutdown();
     return -1;
   }
void cs349::XApplication::Quit ()
Stops the event loop.
Definition at line 98 of file XApplication.cpp.
References quit.
Referenced by Run().
   {
     quit = true;
   }
void cs349::XApplication::Run ()
Starts the application event loop. This will run until "Quit" is called or the user closes the window.
Definition at line 145 of file XApplication.cpp.
References ErrorHandler, LOG_TODO, quit, Quit(), and scheme_interpreter_service().
Referenced by main().
   {
     XSetIOErrorHandler(ErrorHandler);
     /*
      * This is where you will implement the event loop. The basic
      * logic of the event loop is as follows:
      * - You should service the CS349 Scheme interpreter to ensure it
      *   progresses (executes any scripts, accepts any user keyboard
      *   input) (already done for you)
      * - Check the return code for scheme_interpreter_service. If it
      *   returns a non-zero value, the application should quit
      * - You need to determine whether there are any events pending in
      *   X lib (call CheckForXEvents()). (already done for you)
      * - You should call EventQueue's ProcessNextEvent() method to
      *   process events and service the timers. Note, you should call
      *   this *even if there are no events pending*, since it will
      *   service the timers.
      * - You'll need to flush X using XFlush() at some point so it
      *   actually communicates changes to the X server
      * - You should sleep if there is nothing left to do, so the app
      *   is not throttling the CPU. Before sleeping, make sure you
      *   check whether any X events are pending using XPending(). If
      *   there are, you shouldn't sleep.
      * - If you sleep, sleep for a very small amount of time, say
      *   1/1000 of a second, to enable interactive typing rates on the
      *   console. (See the usleep function for fine-grained sleep
      *   amounts).
      * - We *will* check to ensure your app doesn't throttle the CPU
      *   when idle, so make sure you sleep when there are no events.
      */
     while (!this->quit) {
       int interpreterReturnCode = 0;
       interpreterReturnCode = scheme_interpreter_service();
       if (interpreterReturnCode == 1) {
         this->Quit();
       }
       LOG_TODO << "TODO CS349: Implement event loop in XApplication::Run (remove when implemented)";
 // TODO CS349
     }
   }
Friends And Related Function Documentation
int ErrorHandler (Display * display) friend
This is a callback from X whenever it encounters a serious error (such as when the user closes the window). You can ignore it
Referenced by Run().
Member Data Documentation
Display* cs349::XApplication::display private
A pointer to the display.
Definition at line 38 of file XApplication.h.
Referenced by CheckForXEvents(), GetBlackColor(), GetWhiteColor(), GetXDisplay(), and XApplication().
EventQueue cs349::XApplication::eventQueue private
The event queue used to manage events.
Definition at line 41 of file XApplication.h.
Referenced by CheckForXEvents(), and GetEventQueue().
bool cs349::XApplication::quit private
Whether the app should continue to run, or quit.
Definition at line 40 of file XApplication.h.
Referenced by Quit(), Run(), and XApplication().
XApplication * cs349::XApplication::s_Instance = NULL static private
Definition at line 36 of file XApplication.h.
Referenced by GetInstance().
int cs349::XApplication::screen private
Represents the default screen to display on.
Definition at line 39 of file XApplication.h.
Referenced by GetBlackColor(), GetDefaultScreen(), GetWhiteColor(), and XApplication().
The documentation for this class was generated from the following files:
XApplication.h
XApplication.cpp