CS349 WatGUI: demo_main.cpp File Reference
demo_main.cpp File Reference
#include <string.h>
#include "XApplication.h"
#include "XWindow.h"
#include "SchemeInterpreter.h"
#include "SchemeComponent.h"
#include "Logging.h"
Classes
class Clock
Functions
int main (int argc, char *argv[])
Variables
const char * scheme_init_fname = "init.scm"
const char * cs349_init_fname = "cs349_init.scm"
Function Documentation
int main (int argc, char * argv[])
Definition at line 54 of file demo_main.cpp.
References cs349::Component::AddComponent(), cs349_init_fname, cs349::XApplication::GetEventQueue(), LOG_DEBUG, cs349::XApplication::Run(), scheme_init_fname, scheme_interpreter_init(), scheme_interpreter_shutdown(), cs349::Component::SetBounds(), cs349::XWindow::SetVisible(), and cs349::Component::SetVisible().
 {
   FLAGS_logtostderr = 1;
   //  FLAGS_log_dir = "./log";
   google::InitGoogleLogging(argv[0]);
   LOG_DEBUG << "Starting up main.cpp";
   XApplication* app = XApplication::GetInstance();
   scheme_interpreter_init(scheme_init_fname, cs349_init_fname, argc, argv);
   XWindow* window = new XWindow(string("My Test Window"), Rectangle(50, 50, 450, 450));
   Clock* clock = new Clock(app->GetEventQueue());
   SchemeComponent* schemeComponent = new SchemeComponent("Scheme Component");
   clock->SetBounds(Rectangle(10, 10, 200, 30));
   schemeComponent->SetBounds(Rectangle(0, 40, 450, 400));
   window->AddComponent(clock);
   window->AddComponent(schemeComponent);
   clock->SetVisible(true);
   schemeComponent->SetVisible(true);
   window->SetVisible(true);
   app->Run();
   vector<XWindow*> windows = XWindow::GetWindowList();
   for (vector<XWindow*>::iterator win = windows.begin(); win != windows.end(); win++) {
     delete (*win);
   }
   delete app;
   return scheme_interpreter_shutdown();
 }
Variable Documentation
const char* cs349_init_fname = "cs349_init.scm"
Definition at line 13 of file demo_main.cpp.
const char* scheme_init_fname = "init.scm"
Definition at line 12 of file demo_main.cpp.