CS349 WatGUI: EventQueueUnitTests.cpp File Reference
EventQueueUnitTests.cpp File Reference
#include "EventQueue.h"
#include "gtest/gtest.h"
#include "Logging.h"
#include <unistd.h>
Classes
class MemoryTrackingEvent
class MemoryTrackingTimer
class TimerListenerCounter
Functions
TEST (EventQueueTests, EventQueuing)
TEST (EventQueueTests, EventQueueDestructorTest)
TEST (EventQueueTests, TimerTests)
Function Documentation
TEST (EventQueueTests , EventQueuing)
Definition at line 38 of file EventQueueUnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::EventQueue::GetNumEventsInQueue(), MemoryTrackingEvent::num_allocated, MemoryTrackingEvent::num_dispatches, and cs349::EventQueue::ProcessNextEvent().
{
   // Test that events are queued properly
   EventQueue eventQueue;
   EXPECT_EQ(0, eventQueue.GetNumEventsInQueue());
   EXPECT_EQ(0, MemoryTrackingEvent::num_allocated);
   MemoryTrackingEvent* event = new MemoryTrackingEvent();
   EXPECT_EQ(1, MemoryTrackingEvent::num_allocated);
   EXPECT_EQ(0, MemoryTrackingEvent::num_dispatches);
   eventQueue.AddEventToQueue(event);
   EXPECT_EQ(1, eventQueue.GetNumEventsInQueue());
   eventQueue.ProcessNextEvent();
   EXPECT_EQ(0, eventQueue.GetNumEventsInQueue());
   EXPECT_EQ(0, MemoryTrackingEvent::num_allocated);
   EXPECT_EQ(1, MemoryTrackingEvent::num_dispatches);
 }
TEST (EventQueueTests , EventQueueDestructorTest)
Definition at line 57 of file EventQueueUnitTests.cpp.
References cs349::EventQueue::AddEventToQueue(), cs349::EventQueue::GetNumEventsInQueue(), and MemoryTrackingEvent::num_allocated.
{
   // Test that events are properly deleted on destruction
   EventQueue* eventQueue = new EventQueue();
   EXPECT_EQ(0, MemoryTrackingEvent::num_allocated);
   MemoryTrackingEvent* event = new MemoryTrackingEvent();
   EXPECT_EQ(1, MemoryTrackingEvent::num_allocated);
   eventQueue->AddEventToQueue(event);
   EXPECT_EQ(1, eventQueue->GetNumEventsInQueue());
   delete eventQueue;
   EXPECT_EQ(0, MemoryTrackingEvent::num_allocated);
 }
TEST (EventQueueTests , TimerTests)
Definition at line 106 of file EventQueueUnitTests.cpp.
References cs349::EventQueue::GetNumEventsInQueue(), cs349::EventQueue::GetNumTimers(), cs349::Timer::IsRunning(), MemoryTrackingTimer::num_allocated, TimerListenerCounter::num_times_called, cs349::EventQueue::ProcessNextEvent(), and cs349::Timer::Start().
{
   // Test timers function as expected on event queue (e.g., that they
   // are serviced on a regular basis)
   const long SLEEP_TIME = 1000000/1000;
   EventQueue* eventQueue = new EventQueue();
   TimerListenerCounter repeatingListener;
   TimerListenerCounter oneShotListener;
   EXPECT_EQ(0, MemoryTrackingTimer::num_allocated);
   MemoryTrackingTimer* repeatingTimer = new MemoryTrackingTimer(eventQueue, 0, true, &repeatingListener);
   MemoryTrackingTimer* oneShotTimer   = new MemoryTrackingTimer(eventQueue, 0, false, &oneShotListener);
   EXPECT_EQ(2, MemoryTrackingTimer::num_allocated);
   EXPECT_EQ(0, eventQueue->GetNumTimers());
   EXPECT_EQ(0, repeatingListener.num_times_called);
   EXPECT_EQ(0, oneShotListener.num_times_called);
   EXPECT_FALSE(repeatingTimer->IsRunning());
   EXPECT_FALSE(oneShotTimer->IsRunning());
   EXPECT_FALSE(repeatingTimer->IsRunning());
   EXPECT_FALSE(oneShotTimer->IsRunning());
   repeatingTimer->Start();
   EXPECT_EQ(1, eventQueue->GetNumTimers());
   oneShotTimer->Start();
   EXPECT_EQ(2, eventQueue->GetNumTimers());
   EXPECT_TRUE(repeatingTimer->IsRunning());
   EXPECT_TRUE(oneShotTimer->IsRunning());
   EXPECT_EQ(0, repeatingListener.num_times_called);
   EXPECT_EQ(0, oneShotListener.num_times_called);
   usleep(SLEEP_TIME);
   EXPECT_EQ(0, eventQueue->GetNumEventsInQueue());
   eventQueue->ProcessNextEvent();
   EXPECT_EQ(1, eventQueue->GetNumEventsInQueue());
   EXPECT_EQ(1, repeatingListener.num_times_called);
   EXPECT_EQ(0, oneShotListener.num_times_called);
   EXPECT_EQ(1, eventQueue->GetNumTimers());
   EXPECT_EQ(2, MemoryTrackingTimer::num_allocated);
   EXPECT_TRUE(repeatingTimer->IsRunning());
   EXPECT_FALSE(oneShotTimer->IsRunning());
   eventQueue->ProcessNextEvent();
   EXPECT_EQ(1, oneShotListener.num_times_called);
   EXPECT_EQ(1, eventQueue->GetNumTimers());
   EXPECT_EQ(2, MemoryTrackingTimer::num_allocated);
   EXPECT_TRUE(repeatingTimer->IsRunning());
   EXPECT_FALSE(oneShotTimer->IsRunning());
   usleep(SLEEP_TIME);
   eventQueue->ProcessNextEvent();
   EXPECT_EQ(2, repeatingListener.num_times_called);
   EXPECT_EQ(1, oneShotListener.num_times_called);
   delete eventQueue;
   EXPECT_EQ(2, MemoryTrackingTimer::num_allocated);
   EXPECT_TRUE(repeatingTimer->IsRunning());
   EXPECT_FALSE(oneShotTimer->IsRunning());
   delete repeatingTimer;
   EXPECT_EQ(1, MemoryTrackingTimer::num_allocated);
   delete oneShotTimer;
   EXPECT_EQ(0, MemoryTrackingTimer::num_allocated);
 }