CS349 WatGUI: SchemeGUI.cpp File Reference
SchemeGUI.cpp File Reference
#include "SchemeGUI.h"
#include "SchemeAffineTransform.h"
#include "SchemeUtils.h"
#include "XApplication.h"
#include "XWindow.h"
#include "SchemeComponent.h"
#include "KeyEvent.h"
#include "MouseEvent.h"
#include "PaintEvent.h"
#include "Logging.h"
#include <unistd.h>
Namespaces
cs349
Constant Groups
cs349
Functions
vector< long > cs349::component_list_to_id_list (const vector< Component * > &components)
vector< long > cs349::window_list_to_id_list (const vector< XWindow * > &windows)
XWindow * cs349::get_xwindow (scheme *sc, pointer args, int pos)
Component * cs349::get_component (scheme *sc, pointer args, int pos)
SchemeComponent * cs349::get_scheme_component (scheme *sc, pointer args, int pos)
pointer cs349::scheme_call_c_function (scheme *sc, pointer args)
pointer cs349::marshall_logging_call (scheme *sc, pointer args, const string &fn_name)
pointer cs349::marshall_xwindow_call (scheme *sc, pointer args, const string &fn_name)
pointer cs349::marshall_graphics_call (scheme *sc, pointer args, const string &fn_name)
pointer cs349::marshall_component_call (scheme *sc, pointer args, const string &fn_name)
pointer cs349::marshall_sc_component_call (scheme *sc, pointer args, const string &fn_name)
pointer cs349::scheme_xwindow_new (scheme *sc, pointer args)
pointer cs349::scheme_get_xwindow_list (scheme *sc, pointer args)
pointer cs349::scheme_graphics_draw_line (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_line_segments (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_point (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_points (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_polygon (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_rect (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_draw_text (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_fill_polygon (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_fill_rect (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_set_background_color (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_set_foreground_color (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_set_clip_rect (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_graphics_set_transform (scheme *sc, pointer args, Graphics *g)
pointer cs349::scheme_component_is_point_in_component (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_background_color (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_foreground_color (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_bounds (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_location (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_size (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_set_visible (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_add_component (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_component_remove_component (scheme *sc, pointer args, Component *component)
pointer cs349::scheme_sc_component_is_scheme_component (scheme *sc, pointer args)
pointer cs349::scheme_sc_component_new (scheme *sc, pointer args)
pointer cs349::scheme_sc_component_add_instruction (scheme *sc, pointer args, SchemeComponent *component)
pointer cs349::scheme_sc_component_get_instructions (scheme *sc, pointer args, SchemeComponent *component)
pointer cs349::scheme_sc_component_set_instructions (scheme *sc, pointer args, SchemeComponent *component)
pointer cs349::scheme_simulate_key_event (scheme *sc, pointer args)
pointer cs349::scheme_simulate_mouse_event (scheme *sc, pointer args)
pointer cs349::scheme_simulate_paint_event (scheme *sc, pointer args)
pointer cs349::scheme_sleep (scheme *sc, pointer args)
pointer cs349::scheme_usleep (scheme *sc, pointer args)
int scheme_install_gui_procedures (scheme *sc)
Function Documentation
int scheme_install_gui_procedures (scheme * sc)
Installs a set of routines for marshalling data to/from the Scheme interpreter for Graphics objects, Components, SchemeComponents, and TurtleGraphics.
Definition at line 103 of file SchemeGUI.cpp.
References cs349::scheme_call_c_function(), cs349::scheme_get_xwindow_list(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), cs349::scheme_sleep(), and cs349::scheme_usleep().
Referenced by scheme_interpreter_init().
{
   scheme_define(sc, sc->global_env, mk_symbol(sc, "_scheme-call-c-function"),
                 mk_foreign_func(sc, scheme_call_c_function));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "get-xwindow-list"),
                 mk_foreign_func(sc, scheme_get_xwindow_list));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-key-event"),
                 mk_foreign_func(sc, scheme_simulate_key_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-mouse-event"),
                 mk_foreign_func(sc, scheme_simulate_mouse_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-paint-event"),
                 mk_foreign_func(sc, scheme_simulate_paint_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "sleep"),
                 mk_foreign_func(sc, scheme_sleep));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "usleep"),
                 mk_foreign_func(sc, scheme_usleep));
   return 0;
 }