CS349 WatGUI: SchemeInterpreter.c File Reference
SchemeInterpreter.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/select.h>
#include <readline/readline.h>
#include <readline/history.h>
#include "scheme/tinyscheme/scheme-private.h"
#include "scheme/tinyscheme/scheme.h"
#include "SchemeInterpreter.h"
#include "SchemeAffineTransform.h"
#include "SchemeGUI.h"
#include "scheme/tinyscheme/scheme.c"
Functions
int init_interpreter (scheme *sc, const char *scheme_init_fname)
int load_scheme_script (scheme *sc, const char *fname)
void run_cmd_line_scripts (scheme *sc, int argc, char **argv)
void init_readline ()
int handle_ctrl_g (int count, int key)
void readline_callback (char *new_line)
void update_cur_input (char **cur_input, const char *new_line)
int scheme_interpreter_service ()
int scheme_interpreter_execute_string (const char *s)
int scheme_interpreter_evaluate_string (const char *s, scheme **outSC, pointer *outResults)
int scheme_interpreter_execute_file (const char *scheme_file_name)
int scheme_interpreter_execute_graphics_instruction (long window_id, const char *op_args_list_string)
int scheme_interpreter_init (const char *scheme_init_fname, const char *cs349_init_fname, int argc, char **argv)
int scheme_interpreter_shutdown ()
Variables
scheme sc
int ready_to_submit = 0
char * cur_input = NULL
int got_EOF = 0
const char * PROMPT = "ts> "
Function Documentation
int handle_ctrl_g (int count, int key)
Definition at line 89 of file SchemeInterpreter.c.
References ready_to_submit.
Referenced by init_readline().
{
   ready_to_submit = 1;
   rl_done = 1;
   printf("\n");
   return 0;
 }
int init_interpreter (scheme * sc, const char * scheme_init_fname)
Definition at line 44 of file SchemeInterpreter.c.
References load_scheme_script().
Referenced by scheme_interpreter_init().
{
   if(!scheme_init(sc)) {
     fprintf(stderr,"Could not initialize interpreter!\n");
     return -1;
   }
   scheme_set_output_port_file(sc, stdout);
   return load_scheme_script(sc, scheme_init_fname);
 }
void init_readline ()
Definition at line 82 of file SchemeInterpreter.c.
References handle_ctrl_g().
Referenced by scheme_interpreter_init().
                      {
   const int CTRL_G = 7; /* ASCII value for Ctrl-G */
   rl_unbind_key(CTRL_G);
   rl_bind_key(CTRL_G, handle_ctrl_g);
   rl_variable_bind("blink-matching-paren","on");
 }
int load_scheme_script (scheme * sc, const char * fname)
Definition at line 53 of file SchemeInterpreter.c.
Referenced by init_interpreter(), run_cmd_line_scripts(), scheme_interpreter_execute_file(), and scheme_interpreter_init().
{
   FILE* fin = NULL;
   fin = fopen(fname, "r");
   if (!fin) {
     fprintf(stderr, "Could not open file %s\n", fname);
     return -1;
   } else {
     scheme_load_named_file(sc, fin, fname);
     fclose(fin);
     fin = NULL;
     if (sc->retcode != 0) {
       fprintf(stderr,"Errors encountered reading %s\n", fname);
     }
     return sc->retcode;
   }
   return 0;
 }
void readline_callback (char * new_line)
Definition at line 96 of file SchemeInterpreter.c.
References cur_input, got_EOF, ready_to_submit, and update_cur_input().
Referenced by scheme_interpreter_init(), and scheme_interpreter_service().
{
   if (!new_line) {
     free(cur_input);
     cur_input = NULL;
     got_EOF = 1;
     rl_callback_handler_remove();
     return;
   }
   if (strlen(new_line) > 0) {
     update_cur_input(&cur_input, new_line);
     add_history(new_line);
   }
   if (strlen(new_line) == 0) {
     ready_to_submit = 1;
   }
   free(new_line);
   new_line = NULL;
   if (!ready_to_submit) {
     rl_set_prompt("... ");
   } else {
     rl_callback_handler_remove(); /* Remove the handler to re-install
                                      it after the interpreter's output
                                      has been printed
                                   */
   }
 }
void run_cmd_line_scripts (scheme * sc, int argc, char ** argv)
Definition at line 71 of file SchemeInterpreter.c.
References load_scheme_script().
Referenced by scheme_interpreter_init().
{
   /* Execute any files specified on command line */
   if (argc > 1) {
     int i;
     for (i = 1; i < argc; i++) {
       const char* fname = argv[i];
       load_scheme_script(sc, fname);
     }
   }
 }
int scheme_interpreter_evaluate_string (const char * s, scheme ** outSC, pointer * outResults)
Evaluates the string represented by s and returns the result (along with a pointer to the Scheme interpreter) via the arguments sc and results.
Returns
0 if no error on evaluating string, non-zero on error
Definition at line 183 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), and cs349::SchemeComponent::HandleMouseEvent().
 {
   scheme_load_string_silent(&sc, s);
   if (outSC != NULL) {
     (*outSC) = &sc;
   }
   if (outResults != NULL) {
     (*outResults) = sc.value;
   }
   return 0;
 }
int scheme_interpreter_execute_file (const char * scheme_file_name)
Executes the code found in the given file.
Returns
0 if no error, non-zero on error
Definition at line 196 of file SchemeInterpreter.c.
References load_scheme_script(), and sc.
{
   return load_scheme_script(&sc, scheme_file_name);
 }
int scheme_interpreter_execute_graphics_instruction (long window_id, const char * op_args_list_string)
This is a special-purpose function for executing a graphics operation.
Definition at line 200 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::SchemeComponent::PaintComponent().
{
   scheme_eval(&sc, cons(&sc, mk_symbol(&sc, "scheme-component-execute-instruction"),
                        cons(&sc, mk_integer(&sc, window_id),
                             cons(&sc, mk_string(&sc, op_args_list_string), sc.NIL))));
   return 0;
 }
int scheme_interpreter_execute_string (const char * s)
Executes the set of commands specified by s.
Returns
0 if no error, non-zero on error
Definition at line 178 of file SchemeInterpreter.c.
References sc.
{
   scheme_load_string(&sc, s);
   return 0;
 }
int scheme_interpreter_init (const char * scheme_init_fname, const char * cs349_init_fname, int argc, char ** argv)
Series of routines to install and manage the TinyScheme interpreter. Only one interpreter can be run at a time. Author: Michael Terry Initializes the interpreter.
Parameters
scheme_init_fname The init.scm file used to read in common Scheme definitions
cs349_init_fname The cs349_init.scm file that contains useful definitions for working with the GUI toolkit
argc Command-line argument count
argv Command-line arguments. Used for executing files named on the command line.
Returns
0 if no error, non-zero on error
Definition at line 207 of file SchemeInterpreter.c.
References init_interpreter(), init_readline(), load_scheme_script(), PROMPT, readline_callback(), run_cmd_line_scripts(), sc, scheme_install_affine_procedures(), and scheme_install_gui_procedures().
Referenced by main().
{
   int retcode = 0;
   retcode = init_interpreter(&sc, scheme_init_fname);
   if (retcode != 0) {
     return retcode;
   }
   scheme_install_affine_procedures(&sc);
   scheme_install_gui_procedures(&sc);
   load_scheme_script(&sc, cs349_init_fname);
   run_cmd_line_scripts(&sc, argc, argv);
   init_readline();
   printf("\n");
   printf("TinyScheme 1.41 Interpreter\n\n");
   printf("Press RETURN twice or CTRL-G to submit input to the interpreter.\n");
   printf("Press CTRL-D to exit the interpreter.\n\n");
   rl_callback_handler_install(PROMPT, readline_callback);
   return retcode;
 }
int scheme_interpreter_service ()
Must be called regularly to check for keyboard input and to allow the scheme interpreter to run.
Returns
0 if no error, 1 if the user entered Ctrl-D on the terminal (indicating the app should quit), and a negative value on error.
Definition at line 143 of file SchemeInterpreter.c.
References cur_input, got_EOF, PROMPT, readline_callback(), ready_to_submit, and sc.
Referenced by cs349::XApplication::Run().
{
   fd_set fds;
   int retval = 0;
   struct timeval timeout;
   FD_ZERO(&fds);
   FD_SET(fileno(stdin), &fds);
   timeout.tv_sec  = 0;
   timeout.tv_usec = 0;
   retval = select(fileno(stdin)+1, &fds, NULL, NULL, &timeout);
   if (retval < 0) {
     fprintf(stderr, "Error selecting on stdin\n");
     return retval;
   } else if (retval == 0) {
     ; /* Timeout. Ignore. */
   } else if (FD_ISSET(fileno(stdin), &fds)) {
     rl_callback_read_char();
   }
   if (ready_to_submit) {
     ready_to_submit = 0;
     if (cur_input != NULL) {
       scheme_load_string(&sc, cur_input);
       printf("\n");
       free(cur_input);
       cur_input = NULL;
     }
     rl_callback_handler_install(PROMPT, readline_callback);
   }
   if (got_EOF) {
     return 1;
   }
   return 0;
 }
int scheme_interpreter_shutdown ()
Call when ready to shut down the app. After calling this, do not call scheme_interpreter_service() anymore.
Returns
The interpreter's return code.
Definition at line 227 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::XApplication::HandleXError(), and main().
{
   int retcode = 0;
   rl_callback_handler_remove();
   retcode = sc.retcode;
   scheme_deinit(&sc);
   return retcode;
 }
void update_cur_input (char ** cur_input, const char * new_line)
Definition at line 123 of file SchemeInterpreter.c.
Referenced by readline_callback().
{
   /* And this code is why programming in C is no picnic. I mean, all
      I want to do is concatenate and/or assign some new strings safely.
      How hard can that be? Here's your answer... */
   if (*cur_input == 0) {
     *cur_input = malloc(strlen(new_line)+1);
     strcpy(*cur_input, new_line);
   } else {
     size_t new_str_size = strlen(*cur_input)+strlen(new_line)+2; /* 2: 1 for terminating character, 1 for newline */
     char* new_str = malloc(new_str_size);
     int result = 0;
     result = snprintf(new_str, new_str_size, "%s\n%s", *cur_input, new_line);
     free(*cur_input);
     *cur_input = new_str;
     if (result < 0 || result >= new_str_size) {
       fprintf(stderr, "Error concatenating strings: %d/%ld\n", result, new_str_size);
     }
   }
 }
Variable Documentation
char* cur_input = NULL
Definition at line 31 of file SchemeInterpreter.c.
Referenced by readline_callback(), and scheme_interpreter_service().
int got_EOF = 0
Definition at line 32 of file SchemeInterpreter.c.
Referenced by readline_callback(), and scheme_interpreter_service().
const char* PROMPT = "ts> "
Definition at line 33 of file SchemeInterpreter.c.
Referenced by scheme_interpreter_init(), and scheme_interpreter_service().
int ready_to_submit = 0
Definition at line 26 of file SchemeInterpreter.c.
Referenced by handle_ctrl_g(), readline_callback(), and scheme_interpreter_service().
scheme sc
This program uses GNU readline, and hence is licensed under the GPL. Portions of this code derived from TinyScheme's scheme.c Author: Michael Terry
Definition at line 25 of file SchemeInterpreter.c.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), cs349::SchemeComponent::HandleMouseEvent(), scheme_interpreter_evaluate_string(), scheme_interpreter_execute_file(), scheme_interpreter_execute_graphics_instruction(), scheme_interpreter_execute_string(), scheme_interpreter_init(), scheme_interpreter_service(), and scheme_interpreter_shutdown().