CS349 WatGUI: SchemeUtils.h File Reference
SchemeUtils.h File Reference
#include <vector>
#include <string>
#include "scheme/tinyscheme/scheme.h"
#include "scheme/tinyscheme/scheme-private.h"
#include "Point.h"
#include "Rectangle.h"
#include "AffineTransform.h"
Functions
bool scheme_has_arg_num (scheme *sc, pointer args, int arg_num)
bool scheme_get_arg_num (scheme *sc, pointer args, int arg_num, pointer *out)
int scheme_get_list_length (scheme *sc, pointer list_ptr)
bool scheme_extract_bool (scheme *sc, pointer args, int position, bool *out)
bool scheme_extract_char (scheme *sc, pointer args, int position, char *out)
bool scheme_extract_long (scheme *sc, pointer args, int position, long *out)
bool scheme_extract_double (scheme *sc, pointer args, int position, double *out)
bool scheme_extract_point (scheme *sc, pointer args, int position, Point *out)
bool scheme_extract_rect (scheme *sc, pointer args, int position, Rectangle *out)
bool scheme_extract_matrix (scheme *sc, pointer args, int position, SquareMatrix *out)
bool scheme_extract_point_list (scheme *sc, pointer args, int position, vector< Point > *out)
bool scheme_extract_string (scheme *sc, pointer args, int position, string *out)
bool scheme_extract_string_list (scheme *sc, pointer args, int position, vector< string > *out)
pointer scheme_long_vector_to_list (scheme *sc, const vector< long > &v)
pointer scheme_double_vector_to_list (scheme *sc, const vector< double > &v)
pointer scheme_string_vector_to_list (scheme *sc, const vector< string > &v)
pointer scheme_rectangle_to_list (scheme *sc, const Rectangle &rect)
pointer scheme_point_to_list (scheme *sc, const Point &point)
pointer scheme_matrix_to_lists (scheme *sc, const SquareMatrix &matrix)
Function Documentation
pointer scheme_double_vector_to_list (scheme * sc, const vector< double > & v)
Definition at line 288 of file SchemeUtils.cpp.
Referenced by scheme_point_to_list(), and scheme_rectangle_to_list().
{
   pointer returnList = sc->NIL;
   for (vector<double>::const_reverse_iterator i = v.rbegin(); i != v.rend(); i++) {
     returnList = cons(sc, mk_real(sc, *i), returnList);
   }
   return returnList;
 }
bool scheme_extract_bool (scheme * sc, pointer args, int position, bool * out)
Definition at line 175 of file SchemeUtils.cpp.
References scheme_extract_bool_value(), and scheme_get_arg_num().
Referenced by cs349::scheme_component_set_visible(), and cs349::scheme_simulate_key_event().
{
   pointer val;
   return (scheme_get_arg_num(sc, args, position, &val)
           && scheme_extract_bool_value(sc, val, out));
 }
bool scheme_extract_char (scheme * sc, pointer args, int position, char * out)
Definition at line 181 of file SchemeUtils.cpp.
References scheme_extract_char_value(), and scheme_get_arg_num().
Referenced by cs349::scheme_simulate_key_event().
{
   pointer val;
   return (scheme_get_arg_num(sc, args, position, &val)
           && scheme_extract_char_value(sc, val, out));
 }
bool scheme_extract_double (scheme * sc, pointer args, int position, double * out)
Definition at line 193 of file SchemeUtils.cpp.
References scheme_extract_double_value(), and scheme_get_arg_num().
Referenced by scheme_affine_make_rotation(), scheme_affine_make_scale(), and scheme_affine_make_translate().
{
   pointer val;
   return (scheme_get_arg_num(sc, args, position, &val)
           && scheme_extract_double_value(sc, val, out));
 }
bool scheme_extract_long (scheme * sc, pointer args, int position, long * out)
Definition at line 187 of file SchemeUtils.cpp.
References scheme_extract_long_value(), and scheme_get_arg_num().
Referenced by cs349::get_component(), cs349::get_xwindow(), cs349::marshall_component_call(), cs349::marshall_graphics_call(), cs349::marshall_logging_call(), cs349::scheme_component_set_background_color(), cs349::scheme_component_set_foreground_color(), cs349::scheme_component_set_size(), cs349::scheme_graphics_set_background_color(), cs349::scheme_graphics_set_foreground_color(), cs349::scheme_simulate_mouse_event(), cs349::scheme_sleep(), and cs349::scheme_usleep().
{
   pointer val;
   return (scheme_get_arg_num(sc, args, position, &val)
           && scheme_extract_long_value(sc, val, out));
 }
bool scheme_extract_matrix (scheme * sc, pointer args, int position, SquareMatrix * out)
Definition at line 221 of file SchemeUtils.cpp.
References LOG_ERROR, and scheme_extract_vector_of_double_vectors().
Referenced by scheme_affine_invert(), cs349::scheme_graphics_set_transform(), and scheme_matrix_multiply().
{
   DoubleLists lists;
   if (!scheme_extract_vector_of_double_vectors(sc, args, position, 3, &lists)) {
     return false;
   }
   if (lists.size() < 3) {
     LOG_ERROR << "Error: Not enough rows in matrix";
     return false;
   }
   for (unsigned int row = 0; row < out->getRows(); row++) {
     for (unsigned int col = 0; col < out->getCols(); col++) {
       (*out)[row][col] = lists[row][col];
     }
   }
   return true;
 }
bool scheme_extract_point (scheme * sc, pointer args, int position, Point * out)
Definition at line 199 of file SchemeUtils.cpp.
References scheme_extract_double_vector(), cs349::Point::x, and cs349::Point::y.
Referenced by cs349::scheme_component_is_point_in_component(), cs349::scheme_component_set_location(), cs349::scheme_graphics_draw_line(), cs349::scheme_graphics_draw_point(), cs349::scheme_graphics_draw_text(), scheme_matrix_multiply(), and cs349::scheme_simulate_mouse_event().
{
   vector<double> values;
   if (!scheme_extract_double_vector(sc, args, position, 2, &values)) {
     return false;
   }
   out->x = values[0];
   out->y = values[1];
   return true;
 }
bool scheme_extract_point_list (scheme * sc, pointer args, int position, vector< Point > * out)
Definition at line 238 of file SchemeUtils.cpp.
References scheme_extract_vector_of_double_vectors().
Referenced by cs349::scheme_graphics_draw_line_segments(), cs349::scheme_graphics_draw_points(), cs349::scheme_graphics_draw_polygon(), and cs349::scheme_graphics_fill_polygon().
{
   DoubleLists lists;
   if (!scheme_extract_vector_of_double_vectors(sc, args, position, 2, &lists)) {
     return false;
   }
   for (DoubleLists::iterator i = lists.begin(); i != lists.end(); i++) {
     out->push_back(Point((*i)[0], (*i)[1]));
   }
   return true;
 }
bool scheme_extract_rect (scheme * sc, pointer args, int position, Rectangle * out)
Definition at line 209 of file SchemeUtils.cpp.
References cs349::Rectangle::height, scheme_extract_double_vector(), cs349::Rectangle::width, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by cs349::scheme_component_set_bounds(), cs349::scheme_graphics_draw_rect(), cs349::scheme_graphics_fill_rect(), cs349::scheme_graphics_set_clip_rect(), cs349::scheme_simulate_paint_event(), and cs349::scheme_xwindow_new().
{
   vector<double> values;
   if (!scheme_extract_double_vector(sc, args, position, 4, &values)) {
     return false;
   }
   out->x      = values[0];
   out->y      = values[1];
   out->width  = values[2];
   out->height = values[3];
   return true;
 }
bool scheme_extract_string (scheme * sc, pointer args, int position, string * out)
Definition at line 249 of file SchemeUtils.cpp.
References scheme_extract_string_value(), and scheme_get_arg_num().
Referenced by cs349::scheme_call_c_function(), scheme_extract_string_list(), cs349::scheme_graphics_draw_text(), cs349::scheme_sc_component_add_instruction(), cs349::scheme_sc_component_new(), and cs349::scheme_xwindow_new().
{
   pointer val;
   return (scheme_get_arg_num(sc, args, position, &val)
           && scheme_extract_string_value(sc, val, out));
 }
bool scheme_extract_string_list (scheme * sc, pointer args, int position, vector< string > * out)
Definition at line 255 of file SchemeUtils.cpp.
References LOG_ERROR, scheme_extract_string(), and scheme_get_arg_num().
Referenced by cs349::scheme_sc_component_set_instructions().
{
   string s;
   pointer slist;
   if (!scheme_get_arg_num(sc, args, position, &slist)) {
     return false;
   }
   if (slist == sc->NIL) {
     return true;
   }
   if (!is_pair(slist)) {
     LOG_ERROR << "Error: Expected string list";
     return false;
   }
   while (slist != sc->NIL) {
     if (!scheme_extract_string(sc, slist, 0, &s)) {
       LOG_ERROR << "Error: Expected string in string list";
       return false;
     }
     out->push_back(s);
     slist = pair_cdr(slist);
   }
   return true;
 }
bool scheme_get_arg_num (scheme * sc, pointer args, int arg_num, pointer * out)
Definition at line 25 of file SchemeUtils.cpp.
References LOG_ERROR, and scheme_get_arg_num().
Referenced by scheme_extract_bool(), scheme_extract_char(), scheme_extract_double(), scheme_extract_double_vector(), scheme_extract_long(), scheme_extract_string(), scheme_extract_string_list(), scheme_extract_vector_of_double_vectors(), scheme_get_arg_num(), and scheme_matrix_multiply().
{
   if (args == sc->NIL || !is_pair(args)) {
     LOG_ERROR << "Error: Not enough arguments to function";
     return false;
   }
   if (arg_num <= 0) {
     (*out) = pair_car(args);
     return true;
   }
   return scheme_get_arg_num(sc, pair_cdr(args), arg_num-1, out);
 }
int scheme_get_list_length (scheme * sc, pointer list_ptr)
Definition at line 37 of file SchemeUtils.cpp.
References scheme_get_list_length().
Referenced by scheme_get_list_length(), cs349::scheme_graphics_draw_line_segments(), and scheme_matrix_multiply().
{
   if (list_ptr == sc->NIL) {
     return 0;
   }
   if (!is_pair(list_ptr)) {
     return -1;
   }
   return 1 + scheme_get_list_length(sc, pair_cdr(list_ptr));
 }
bool scheme_has_arg_num (scheme * sc, pointer args, int arg_num)
Definition at line 15 of file SchemeUtils.cpp.
References scheme_has_arg_num().
Referenced by scheme_has_arg_num().
{
   if (arg_num <= 0) {
     return true;
   }
   if (args == sc->NIL || !is_pair(args)) {
     return false;
   }
   return scheme_has_arg_num(sc, pair_cdr(args), arg_num-1);
 }
pointer scheme_long_vector_to_list (scheme * sc, const vector< long > & v)
Definition at line 280 of file SchemeUtils.cpp.
Referenced by cs349::marshall_xwindow_call(), and cs349::scheme_get_xwindow_list().
{
   pointer returnList = sc->NIL;
   for (vector<long>::const_reverse_iterator i = v.rbegin(); i != v.rend(); i++) {
     returnList = cons(sc, mk_integer(sc, *i), returnList);
   }
   return returnList;
 }
pointer scheme_matrix_to_lists (scheme * sc, const SquareMatrix & matrix)
Definition at line 313 of file SchemeUtils.cpp.
Referenced by cs349::marshall_graphics_call(), scheme_affine_invert(), scheme_affine_make_identity(), scheme_affine_make_rotation(), scheme_affine_make_scale(), scheme_affine_make_translate(), and scheme_matrix_multiply().
{
   pointer matrix_list = sc->NIL;
   for (int row = matrix.getRows()-1; row >= 0; row--) {
     pointer row_list = sc->NIL;
     for (int col = matrix.getCols()-1; col >= 0; col--) {
       row_list = cons(sc, mk_real(sc, matrix[row][col]), row_list);
     }
     matrix_list = cons(sc, row_list, matrix_list);
   }
   return matrix_list;
 }
pointer scheme_point_to_list (scheme * sc, const Point & point)
Definition at line 305 of file SchemeUtils.cpp.
References scheme_double_vector_to_list(), cs349::Point::x, and cs349::Point::y.
Referenced by scheme_matrix_multiply().
{
   vector<double> doubleList;
   doubleList.push_back(point.x);
   doubleList.push_back(point.y);
   return scheme_double_vector_to_list(sc, doubleList);
 }
pointer scheme_rectangle_to_list (scheme * sc, const Rectangle & rect)
Definition at line 296 of file SchemeUtils.cpp.
References cs349::Rectangle::height, scheme_double_vector_to_list(), cs349::Rectangle::width, cs349::Rectangle::x, and cs349::Rectangle::y.
Referenced by cs349::marshall_component_call(), and cs349::marshall_graphics_call().
{
   vector<double> doubleList;
   doubleList.push_back(rect.x);
   doubleList.push_back(rect.y);
   doubleList.push_back(rect.width);
   doubleList.push_back(rect.height);
   return scheme_double_vector_to_list(sc, doubleList);
 }
pointer scheme_string_vector_to_list (scheme * sc, const vector< string > & v)
Definition at line 325 of file SchemeUtils.cpp.
Referenced by cs349::marshall_sc_component_call().
{
   pointer returnList = sc->NIL;
   for (vector<string>::const_reverse_iterator i = v.rbegin(); i != v.rend(); i++) {
     returnList = cons(sc, mk_string(sc, i->c_str()), returnList);
   }
   return returnList;
 }