CS349 WatGUI: SchemeAffineTransform.cpp File Reference
SchemeAffineTransform.cpp File Reference
#include "SchemeAffineTransform.h"
#include "AffineTransform.h"
#include "SchemeUtils.h"
Functions
pointer scheme_affine_make_identity (scheme *sc, pointer args)
pointer scheme_affine_make_rotation (scheme *sc, pointer args)
pointer scheme_affine_make_scale (scheme *sc, pointer args)
pointer scheme_affine_make_translate (scheme *sc, pointer args)
pointer scheme_affine_invert (scheme *sc, pointer args)
pointer scheme_matrix_multiply (scheme *sc, pointer args)
int scheme_install_affine_procedures (scheme *sc)
Function Documentation
pointer scheme_affine_invert (scheme * sc, pointer args)
Definition at line 69 of file SchemeAffineTransform.cpp.
References cs349::AffineTransform::GetInverse(), cs349::AffineTransform::GetMatrix(), scheme_extract_matrix(), and scheme_matrix_to_lists().
Referenced by scheme_install_affine_procedures().
{
   SquareMatrix m;
   if (!scheme_extract_matrix(sc, args, 0, &m)) {
     fprintf(stderr, "Error: Need list of lists for affine-invert\n");
     return sc->NIL;
   }
   AffineTransform t(m);
   return scheme_matrix_to_lists(sc, t.GetInverse().GetMatrix());
 }
pointer scheme_affine_make_identity (scheme * sc, pointer args)
Definition at line 32 of file SchemeAffineTransform.cpp.
References cs349::AffineTransform::MakeIdentity(), and scheme_matrix_to_lists().
Referenced by scheme_install_affine_procedures().
{
   return scheme_matrix_to_lists(sc, AffineTransform::MakeIdentity().GetMatrix());
 }
pointer scheme_affine_make_rotation (scheme * sc, pointer args)
Definition at line 36 of file SchemeAffineTransform.cpp.
References cs349::AffineTransform::MakeRotation(), scheme_extract_double(), and scheme_matrix_to_lists().
Referenced by scheme_install_affine_procedures().
{
   double theta;
   if (!scheme_extract_double(sc, args, 0, &theta)) {
     fprintf(stderr, "Error: Need theta parameter for affine-make-rotation\n");
     return sc->NIL;
   }
   return scheme_matrix_to_lists(sc, AffineTransform::MakeRotation(theta).GetMatrix());
 }
pointer scheme_affine_make_scale (scheme * sc, pointer args)
Definition at line 45 of file SchemeAffineTransform.cpp.
References cs349::AffineTransform::MakeScale(), scheme_extract_double(), and scheme_matrix_to_lists().
Referenced by scheme_install_affine_procedures().
{
   double scale_x;
   double scale_y;
   if (!scheme_extract_double(sc, args, 0, &scale_x)
       || !scheme_extract_double(sc, args, 1, &scale_y))
     {
       fprintf(stderr, "Error: Need x and y scale values for affine-make-scale\n");
       return sc->NIL;
     }
   return scheme_matrix_to_lists(sc, AffineTransform::MakeScale(scale_x, scale_y).GetMatrix());
 }
pointer scheme_affine_make_translate (scheme * sc, pointer args)
Definition at line 57 of file SchemeAffineTransform.cpp.
References cs349::AffineTransform::MakeTranslation(), scheme_extract_double(), and scheme_matrix_to_lists().
Referenced by scheme_install_affine_procedures().
{
   double translate_x;
   double translate_y;
   if (!scheme_extract_double(sc, args, 0, &translate_x)
       || !scheme_extract_double(sc, args, 1, &translate_y))
     {
       fprintf(stderr, "Error: Need x and y translation values for affine-make-translate\n");
       return sc->NIL;
     }
   return scheme_matrix_to_lists(sc, AffineTransform::MakeTranslation(translate_x, translate_y).GetMatrix());
 }
int scheme_install_affine_procedures (scheme * sc)
Installs functions to marshall AffineTransforms to/from the Scheme interpreter
Definition at line 16 of file SchemeAffineTransform.cpp.
References scheme_affine_invert(), scheme_affine_make_identity(), scheme_affine_make_rotation(), scheme_affine_make_scale(), scheme_affine_make_translate(), and scheme_matrix_multiply().
Referenced by scheme_interpreter_init().
{
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-identity"),
                                     mk_foreign_func(sc, scheme_affine_make_identity));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-rotation"),
                                     mk_foreign_func(sc, scheme_affine_make_rotation));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-scale"),
                                     mk_foreign_func(sc, scheme_affine_make_scale));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-translation"),
                                     mk_foreign_func(sc, scheme_affine_make_translate));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-invert"),
                                     mk_foreign_func(sc, scheme_affine_invert));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "_matrix-mul"),
                                     mk_foreign_func(sc, scheme_matrix_multiply));
   return 0;
 }
pointer scheme_matrix_multiply (scheme * sc, pointer args)
Definition at line 79 of file SchemeAffineTransform.cpp.
References scheme_extract_matrix(), scheme_extract_point(), scheme_get_arg_num(), scheme_get_list_length(), scheme_matrix_to_lists(), and scheme_point_to_list().
Referenced by scheme_install_affine_procedures().
{
   SquareMatrix l;
   if (!scheme_extract_matrix(sc, args, 0, &l)) {
     fprintf(stderr, "Error: Need matrix as first argument to matrix-mul\n");
     return sc->NIL;
   }
   pointer secondArg;
   if (!scheme_get_arg_num(sc, args, 1, &secondArg)) {
     fprintf(stderr, "Error: Need matrix or point as second argument to matrix-mul\n");
     return sc->NIL;
   }
   if (scheme_get_list_length(sc, secondArg) == 2) {
     Point p;
     if (!scheme_extract_point(sc, args, 1, &p)) {
       fprintf(stderr, "Error: Not a point: Need matrix or point as second argument to matrix-mul\n");
       return sc->NIL;
     }
     AffineTransform left(l);
     return scheme_point_to_list(sc, left * p);
   }
   SquareMatrix r;
   if (!scheme_extract_matrix(sc, args, 1, &r)) {
     fprintf(stderr, "Error: Not a matrix: Need matrix or point as second argument to matrix-mul\n");
     return sc->NIL;
   }
   return scheme_matrix_to_lists(sc, l*r);
 }