CS349 WatGUI: SchemeAffineTransform.h File Reference
SchemeAffineTransform.h File Reference
#include "scheme/tinyscheme/scheme.h"
Functions
int scheme_install_affine_procedures (scheme *sc)
Function Documentation
int scheme_install_affine_procedures (scheme * sc)
Installs functions to marshall AffineTransforms to/from the Scheme interpreter
Definition at line 16 of file SchemeAffineTransform.cpp.
References scheme_affine_invert(), scheme_affine_make_identity(), scheme_affine_make_rotation(), scheme_affine_make_scale(), scheme_affine_make_translate(), and scheme_matrix_multiply().
Referenced by scheme_interpreter_init().
{
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-identity"),
                                     mk_foreign_func(sc, scheme_affine_make_identity));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-rotation"),
                                     mk_foreign_func(sc, scheme_affine_make_rotation));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-scale"),
                                     mk_foreign_func(sc, scheme_affine_make_scale));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-make-translation"),
                                     mk_foreign_func(sc, scheme_affine_make_translate));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "affine-invert"),
                                     mk_foreign_func(sc, scheme_affine_invert));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "_matrix-mul"),
                                     mk_foreign_func(sc, scheme_matrix_multiply));
   return 0;
 }