CS349 WatGUI: SchemeGUI.h File Reference
SchemeGUI.h File Reference
#include "scheme/tinyscheme/scheme.h"
Functions
int scheme_install_gui_procedures (scheme *sc)
Function Documentation
int scheme_install_gui_procedures (scheme * sc)
Installs a set of routines for marshalling data to/from the Scheme interpreter for Graphics objects, Components, SchemeComponents, and TurtleGraphics.
Definition at line 103 of file SchemeGUI.cpp.
References cs349::scheme_call_c_function(), cs349::scheme_get_xwindow_list(), cs349::scheme_simulate_key_event(), cs349::scheme_simulate_mouse_event(), cs349::scheme_simulate_paint_event(), cs349::scheme_sleep(), and cs349::scheme_usleep().
Referenced by scheme_interpreter_init().
{
   scheme_define(sc, sc->global_env, mk_symbol(sc, "_scheme-call-c-function"),
                 mk_foreign_func(sc, scheme_call_c_function));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "get-xwindow-list"),
                 mk_foreign_func(sc, scheme_get_xwindow_list));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-key-event"),
                 mk_foreign_func(sc, scheme_simulate_key_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-mouse-event"),
                 mk_foreign_func(sc, scheme_simulate_mouse_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "simulate-paint-event"),
                 mk_foreign_func(sc, scheme_simulate_paint_event));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "sleep"),
                 mk_foreign_func(sc, scheme_sleep));
   scheme_define(sc, sc->global_env, mk_symbol(sc, "usleep"),
                 mk_foreign_func(sc, scheme_usleep));
   return 0;
 }