CS349 WatGUI: SchemeInterpreter.h File Reference
SchemeInterpreter.h File Reference
#include "scheme/tinyscheme/scheme-private.h"
#include "scheme/tinyscheme/scheme.h"
Functions
int scheme_interpreter_init (const char *scheme_init_fname, const char *cs349_init_fname, int argc, char **argv)
int scheme_interpreter_service ()
int scheme_interpreter_execute_string (const char *s)
int scheme_interpreter_evaluate_string (const char *s, scheme **outSC, pointer *outResults)
int scheme_interpreter_execute_file (const char *scheme_file_name)
int scheme_interpreter_shutdown ()
int scheme_interpreter_execute_graphics_instruction (long window_id, const char *op_args_list_string)
Function Documentation
int scheme_interpreter_evaluate_string (const char * s, scheme ** outSC, pointer * outResults)
Evaluates the string represented by s and returns the result (along with a pointer to the Scheme interpreter) via the arguments sc and results.
Returns
0 if no error on evaluating string, non-zero on error
Definition at line 183 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::SchemeComponent::HandleKeyEvent(), and cs349::SchemeComponent::HandleMouseEvent().
 {
   scheme_load_string_silent(&sc, s);
   if (outSC != NULL) {
     (*outSC) = &sc;
   }
   if (outResults != NULL) {
     (*outResults) = sc.value;
   }
   return 0;
 }
int scheme_interpreter_execute_file (const char * scheme_file_name)
Executes the code found in the given file.
Returns
0 if no error, non-zero on error
Definition at line 196 of file SchemeInterpreter.c.
References load_scheme_script(), and sc.
{
   return load_scheme_script(&sc, scheme_file_name);
 }
int scheme_interpreter_execute_graphics_instruction (long window_id, const char * op_args_list_string)
This is a special-purpose function for executing a graphics operation.
Definition at line 200 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::SchemeComponent::PaintComponent().
{
   scheme_eval(&sc, cons(&sc, mk_symbol(&sc, "scheme-component-execute-instruction"),
                        cons(&sc, mk_integer(&sc, window_id),
                             cons(&sc, mk_string(&sc, op_args_list_string), sc.NIL))));
   return 0;
 }
int scheme_interpreter_execute_string (const char * s)
Executes the set of commands specified by s.
Returns
0 if no error, non-zero on error
Definition at line 178 of file SchemeInterpreter.c.
References sc.
{
   scheme_load_string(&sc, s);
   return 0;
 }
int scheme_interpreter_init (const char * scheme_init_fname, const char * cs349_init_fname, int argc, char ** argv)
Series of routines to install and manage the TinyScheme interpreter. Only one interpreter can be run at a time. Author: Michael Terry Initializes the interpreter.
Parameters
scheme_init_fname The init.scm file used to read in common Scheme definitions
cs349_init_fname The cs349_init.scm file that contains useful definitions for working with the GUI toolkit
argc Command-line argument count
argv Command-line arguments. Used for executing files named on the command line.
Returns
0 if no error, non-zero on error
Definition at line 207 of file SchemeInterpreter.c.
References init_interpreter(), init_readline(), load_scheme_script(), PROMPT, readline_callback(), run_cmd_line_scripts(), sc, scheme_install_affine_procedures(), and scheme_install_gui_procedures().
Referenced by main().
{
   int retcode = 0;
   retcode = init_interpreter(&sc, scheme_init_fname);
   if (retcode != 0) {
     return retcode;
   }
   scheme_install_affine_procedures(&sc);
   scheme_install_gui_procedures(&sc);
   load_scheme_script(&sc, cs349_init_fname);
   run_cmd_line_scripts(&sc, argc, argv);
   init_readline();
   printf("\n");
   printf("TinyScheme 1.41 Interpreter\n\n");
   printf("Press RETURN twice or CTRL-G to submit input to the interpreter.\n");
   printf("Press CTRL-D to exit the interpreter.\n\n");
   rl_callback_handler_install(PROMPT, readline_callback);
   return retcode;
 }
int scheme_interpreter_service ()
Must be called regularly to check for keyboard input and to allow the scheme interpreter to run.
Returns
0 if no error, 1 if the user entered Ctrl-D on the terminal (indicating the app should quit), and a negative value on error.
Definition at line 143 of file SchemeInterpreter.c.
References cur_input, got_EOF, PROMPT, readline_callback(), ready_to_submit, and sc.
Referenced by cs349::XApplication::Run().
{
   fd_set fds;
   int retval = 0;
   struct timeval timeout;
   FD_ZERO(&fds);
   FD_SET(fileno(stdin), &fds);
   timeout.tv_sec  = 0;
   timeout.tv_usec = 0;
   retval = select(fileno(stdin)+1, &fds, NULL, NULL, &timeout);
   if (retval < 0) {
     fprintf(stderr, "Error selecting on stdin\n");
     return retval;
   } else if (retval == 0) {
     ; /* Timeout. Ignore. */
   } else if (FD_ISSET(fileno(stdin), &fds)) {
     rl_callback_read_char();
   }
   if (ready_to_submit) {
     ready_to_submit = 0;
     if (cur_input != NULL) {
       scheme_load_string(&sc, cur_input);
       printf("\n");
       free(cur_input);
       cur_input = NULL;
     }
     rl_callback_handler_install(PROMPT, readline_callback);
   }
   if (got_EOF) {
     return 1;
   }
   return 0;
 }
int scheme_interpreter_shutdown ()
Call when ready to shut down the app. After calling this, do not call scheme_interpreter_service() anymore.
Returns
The interpreter's return code.
Definition at line 227 of file SchemeInterpreter.c.
References sc.
Referenced by cs349::XApplication::HandleXError(), and main().
{
   int retcode = 0;
   rl_callback_handler_remove();
   retcode = sc.retcode;
   scheme_deinit(&sc);
   return retcode;
 }